
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_janela(object):
    def setupUi(self, janela):
        janela.setObjectName("janela")
        janela.resize(475, 644)
        janela.setWindowFlag(QtCore.Qt.WindowStaysOnTopHint)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        janela.setPalette(palette)
        janela.setFocusPolicy(QtCore.Qt.NoFocus)
        janela.setAutoFillBackground(False)
        janela.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(janela)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 481, 601))
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.campo_lista_status = QtWidgets.QComboBox(self.tab_5)
        self.campo_lista_status.setGeometry(QtCore.QRect(290, 130, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.campo_lista_status.setFont(font)
        self.campo_lista_status.setStyleSheet("")
        self.campo_lista_status.setEditable(False)
        self.campo_lista_status.setObjectName("campo_lista_status")
        self.campo_lista_status.addItem("")
        self.campo_lista_status.addItem("")
        self.campo_lista_status.addItem("")
        self.campo_lista_status.addItem("")
        self.label = QtWidgets.QLabel(self.tab_5)
        self.label.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_5)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 241, 16))
        self.label_2.setObjectName("label_2")
        self.campo_data_agendamento = QtWidgets.QDateEdit(self.tab_5)
        self.campo_data_agendamento.setGeometry(QtCore.QRect(230, 30, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.campo_data_agendamento.setFont(font)
        self.campo_data_agendamento.setStyleSheet("")
        self.campo_data_agendamento.setObjectName("campo_data_agendamento")
        self.label_17 = QtWidgets.QLabel(self.tab_5)
        self.label_17.setGeometry(QtCore.QRect(290, 110, 101, 16))
        self.label_17.setObjectName("label_17")
        self.campo_certificado = QtWidgets.QLineEdit(self.tab_5)
        self.campo_certificado.setGeometry(QtCore.QRect(10, 80, 451, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.campo_certificado.setFont(font)
        self.campo_certificado.setText("")
        self.campo_certificado.setObjectName("campo_certificado")
        self.campo_pedido = QtWidgets.QLineEdit(self.tab_5)
        self.campo_pedido.setGeometry(QtCore.QRect(10, 30, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.campo_pedido.setFont(font)
        self.campo_pedido.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.campo_pedido.setText("")
        self.campo_pedido.setObjectName("campo_pedido")
        self.campo_hora_agendamento = QtWidgets.QTimeEdit(self.tab_5)
        self.campo_hora_agendamento.setGeometry(QtCore.QRect(360, 30, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.campo_hora_agendamento.setFont(font)
        self.campo_hora_agendamento.setStyleSheet("")
        self.campo_hora_agendamento.setObjectName("campo_hora_agendamento")
        self.label_4 = QtWidgets.QLabel(self.tab_5)
        self.label_4.setGeometry(QtCore.QRect(350, 10, 111, 16))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.tab_5)
        self.label_3.setGeometry(QtCore.QRect(210, 10, 131, 20))
        self.label_3.setObjectName("label_3")
        self.campo_novo_noBd = QtWidgets.QLabel(self.tab_5)
        self.campo_novo_noBd.setGeometry(QtCore.QRect(180, 30, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(11)
        self.campo_novo_noBd.setFont(font)
        self.campo_novo_noBd.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.campo_novo_noBd.setText("")
        self.campo_novo_noBd.setAlignment(QtCore.Qt.AlignCenter)
        self.campo_novo_noBd.setObjectName("campo_novo_noBd")
        self.campo_lista_status_3 = QtWidgets.QComboBox(self.tab_5)
        self.campo_lista_status_3.setGeometry(QtCore.QRect(10, 130, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.campo_lista_status_3.setFont(font)
        self.campo_lista_status_3.setStyleSheet("")
        self.campo_lista_status_3.setEditable(False)
        self.campo_lista_status_3.setObjectName("campo_lista_status_3")
        self.campo_lista_status_3.addItem("")
        self.campo_lista_status_3.addItem("")
        self.label_22 = QtWidgets.QLabel(self.tab_5)
        self.label_22.setGeometry(QtCore.QRect(10, 110, 111, 16))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.tab_5)
        self.label_23.setGeometry(QtCore.QRect(110, 110, 101, 16))
        self.label_23.setObjectName("label_23")
        self.campo_lista_status_4 = QtWidgets.QComboBox(self.tab_5)
        self.campo_lista_status_4.setGeometry(QtCore.QRect(110, 130, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.campo_lista_status_4.setFont(font)
        self.campo_lista_status_4.setStyleSheet("")
        self.campo_lista_status_4.setEditable(False)
        self.campo_lista_status_4.setObjectName("campo_lista_status_4")
        self.campo_lista_status_4.addItem("")
        self.campo_lista_status_4.setItemText(0, "")
        self.campo_lista_status_4.addItem("")
        self.campo_lista_status_4.addItem("")
        self.botao_terminar = QtWidgets.QPushButton(self.tab_5)
        self.botao_terminar.setGeometry(QtCore.QRect(320, 530, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.botao_terminar.setFont(font)
        self.botao_terminar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_terminar.setStyleSheet("border-radius:10px;\n"
"background-color:rgb(73, 218, 107);")
        self.botao_terminar.setObjectName("botao_terminar")
        self.botao_salvar = QtWidgets.QPushButton(self.tab_5)
        self.botao_salvar.setGeometry(QtCore.QRect(320, 490, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.botao_salvar.setFont(font)
        self.botao_salvar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_salvar.setStyleSheet("border-radius:10px;\n"
"background-color:rgb(0, 180, 210);\n"
"\n"
"")
        self.botao_salvar.setObjectName("botao_salvar")
        self.barra_progresso_pedido = QtWidgets.QProgressBar(self.tab_5)
        self.barra_progresso_pedido.setGeometry(QtCore.QRect(10, 30, 161, 6))
        self.barra_progresso_pedido.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.barra_progresso_pedido.setProperty("value", 0)
        self.barra_progresso_pedido.setAlignment(QtCore.Qt.AlignCenter)
        self.barra_progresso_pedido.setFormat("")
        self.barra_progresso_pedido.setObjectName("barra_progresso_pedido")
        self.label_11 = QtWidgets.QLabel(self.tab_5)
        self.label_11.setGeometry(QtCore.QRect(10, 220, 81, 16))
        self.label_11.setStyleSheet("color: #333;")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_5)
        self.label_12.setGeometry(QtCore.QRect(350, 220, 121, 16))
        self.label_12.setStyleSheet("color: #333;")
        self.label_12.setObjectName("label_12")
        self.botao_consulta_rg = QtWidgets.QPushButton(self.tab_5)
        self.botao_consulta_rg.setGeometry(QtCore.QRect(430, 290, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.botao_consulta_rg.setFont(font)
        self.botao_consulta_rg.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_consulta_rg.setObjectName("botao_consulta_rg")
        self.campo_cnpj = QtWidgets.QLineEdit(self.tab_5)
        self.campo_cnpj.setGeometry(QtCore.QRect(10, 440, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.campo_cnpj.setFont(font)
        self.campo_cnpj.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.campo_cnpj.setText("")
        self.campo_cnpj.setPlaceholderText("")
        self.campo_cnpj.setObjectName("campo_cnpj")
        self.label_18 = QtWidgets.QLabel(self.tab_5)
        self.label_18.setGeometry(QtCore.QRect(10, 370, 141, 20))
        self.label_18.setStyleSheet("color: #333;")
        self.label_18.setObjectName("label_18")
        self.campo_cpf = QtWidgets.QLineEdit(self.tab_5)
        self.campo_cpf.setGeometry(QtCore.QRect(10, 290, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.campo_cpf.setFont(font)
        self.campo_cpf.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.campo_cpf.setText("")
        self.campo_cpf.setPlaceholderText("")
        self.campo_cpf.setObjectName("campo_cpf")
        self.label_10 = QtWidgets.QLabel(self.tab_5)
        self.label_10.setGeometry(QtCore.QRect(250, 270, 81, 16))
        self.label_10.setStyleSheet("color: #333;")
        self.label_10.setObjectName("label_10")
        self.label_14 = QtWidgets.QLabel(self.tab_5)
        self.label_14.setGeometry(QtCore.QRect(10, 420, 111, 20))
        self.label_14.setStyleSheet("color: #333;")
        self.label_14.setObjectName("label_14")
        self.campo_data_nascimento = QtWidgets.QDateEdit(self.tab_5)
        self.campo_data_nascimento.setGeometry(QtCore.QRect(340, 240, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.campo_data_nascimento.setFont(font)
        self.campo_data_nascimento.setStyleSheet("")
        self.campo_data_nascimento.setObjectName("campo_data_nascimento")
        self.campo_nome = QtWidgets.QLineEdit(self.tab_5)
        self.campo_nome.setGeometry(QtCore.QRect(10, 190, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.campo_nome.setFont(font)
        self.campo_nome.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.campo_nome.setText("")
        self.campo_nome.setPlaceholderText("")
        self.campo_nome.setObjectName("campo_nome")
        self.botao_dados_cnpj = QtWidgets.QPushButton(self.tab_5)
        self.botao_dados_cnpj.setGeometry(QtCore.QRect(430, 440, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.botao_dados_cnpj.setFont(font)
        self.botao_dados_cnpj.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_dados_cnpj.setObjectName("botao_dados_cnpj")
        self.botao_consulta_cnh = QtWidgets.QPushButton(self.tab_5)
        self.botao_consulta_cnh.setGeometry(QtCore.QRect(430, 340, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.botao_consulta_cnh.setFont(font)
        self.botao_consulta_cnh.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_consulta_cnh.setObjectName("botao_consulta_cnh")
        self.label_24 = QtWidgets.QLabel(self.tab_5)
        self.label_24.setGeometry(QtCore.QRect(10, 170, 201, 16))
        self.label_24.setStyleSheet("color: #333;")
        self.label_24.setObjectName("label_24")
        self.campo_cnh = QtWidgets.QLineEdit(self.tab_5)
        self.campo_cnh.setGeometry(QtCore.QRect(10, 340, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.campo_cnh.setFont(font)
        self.campo_cnh.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.campo_cnh.setText("")
        self.campo_cnh.setObjectName("campo_cnh")
        self.campo_nome_mae = QtWidgets.QLineEdit(self.tab_5)
        self.campo_nome_mae.setGeometry(QtCore.QRect(10, 390, 451, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.campo_nome_mae.setFont(font)
        self.campo_nome_mae.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.campo_nome_mae.setStyleSheet("")
        self.campo_nome_mae.setText("")
        self.campo_nome_mae.setObjectName("campo_nome_mae")
        self.label_6 = QtWidgets.QLabel(self.tab_5)
        self.label_6.setGeometry(QtCore.QRect(10, 270, 81, 16))
        self.label_6.setStyleSheet("color: #333;")
        self.label_6.setObjectName("label_6")
        self.label_15 = QtWidgets.QLabel(self.tab_5)
        self.label_15.setGeometry(QtCore.QRect(10, 320, 61, 20))
        self.label_15.setStyleSheet("color: #333;")
        self.label_15.setObjectName("label_15")
        self.botao_consulta_cpf = QtWidgets.QPushButton(self.tab_5)
        self.botao_consulta_cpf.setGeometry(QtCore.QRect(210, 290, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.botao_consulta_cpf.setFont(font)
        self.botao_consulta_cpf.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_consulta_cpf.setObjectName("botao_consulta_cpf")
        self.botao_pasta_cliente = QtWidgets.QPushButton(self.tab_5)
        self.botao_pasta_cliente.setGeometry(QtCore.QRect(430, 190, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.botao_pasta_cliente.setFont(font)
        self.botao_pasta_cliente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_pasta_cliente.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botao_pasta_cliente.setObjectName("botao_pasta_cliente")
        self.campo_email = QtWidgets.QLineEdit(self.tab_5)
        self.campo_email.setGeometry(QtCore.QRect(10, 240, 321, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.campo_email.setFont(font)
        self.campo_email.setText("")
        self.campo_email.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.campo_email.setPlaceholderText("")
        self.campo_email.setObjectName("campo_email")
        self.campo_rg = QtWidgets.QLineEdit(self.tab_5)
        self.campo_rg.setGeometry(QtCore.QRect(250, 290, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.campo_rg.setFont(font)
        self.campo_rg.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.campo_rg.setPlaceholderText("")
        self.campo_rg.setObjectName("campo_rg")
        self.label_16 = QtWidgets.QLabel(self.tab_5)
        self.label_16.setGeometry(QtCore.QRect(250, 320, 201, 20))
        self.label_16.setStyleSheet("color: #333;")
        self.label_16.setObjectName("label_16")
        self.campo_seguranca_cnh = QtWidgets.QLineEdit(self.tab_5)
        self.campo_seguranca_cnh.setGeometry(QtCore.QRect(250, 340, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.campo_seguranca_cnh.setFont(font)
        self.campo_seguranca_cnh.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.campo_seguranca_cnh.setObjectName("campo_seguranca_cnh")
        self.campo_cnpj_municipio = QtWidgets.QLineEdit(self.tab_5)
        self.campo_cnpj_municipio.setEnabled(True)
        self.campo_cnpj_municipio.setGeometry(QtCore.QRect(180, 440, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.campo_cnpj_municipio.setFont(font)
        self.campo_cnpj_municipio.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.campo_cnpj_municipio.setText("")
        self.campo_cnpj_municipio.setPlaceholderText("")
        self.campo_cnpj_municipio.setObjectName("campo_cnpj_municipio")
        self.campo_cnpj_uf = QtWidgets.QLineEdit(self.tab_5)
        self.campo_cnpj_uf.setEnabled(True)
        self.campo_cnpj_uf.setGeometry(QtCore.QRect(320, 440, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.campo_cnpj_uf.setFont(font)
        self.campo_cnpj_uf.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.campo_cnpj_uf.setText("")
        self.campo_cnpj_uf.setPlaceholderText("")
        self.campo_cnpj_uf.setObjectName("campo_cnpj_uf")
        self.label_25 = QtWidgets.QLabel(self.tab_5)
        self.label_25.setGeometry(QtCore.QRect(180, 420, 171, 16))
        self.label_25.setStyleSheet("color: #333;")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.tab_5)
        self.label_26.setGeometry(QtCore.QRect(320, 420, 51, 20))
        self.label_26.setStyleSheet("color: #333;")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.tab_5)
        self.label_27.setGeometry(QtCore.QRect(10, 470, 131, 16))
        self.label_27.setStyleSheet("color: #333;")
        self.label_27.setObjectName("label_27")
        self.campo_diretorio_pasta = QtWidgets.QTextEdit(self.tab_5)
        self.campo_diretorio_pasta.setGeometry(QtCore.QRect(10, 490, 301, 71))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.campo_diretorio_pasta.setFont(font)
        self.campo_diretorio_pasta.setObjectName("campo_diretorio_pasta")
        self.botao_consulta_cnpj = QtWidgets.QPushButton(self.tab_5)
        self.botao_consulta_cnpj.setGeometry(QtCore.QRect(400, 440, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.botao_consulta_cnpj.setFont(font)
        self.botao_consulta_cnpj.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_consulta_cnpj.setObjectName("botao_consulta_cnpj")
        self.campo_lista_status.raise_()
        self.campo_data_agendamento.raise_()
        self.label_17.raise_()
        self.campo_certificado.raise_()
        self.campo_pedido.raise_()
        self.campo_hora_agendamento.raise_()
        self.label_4.raise_()
        self.label_3.raise_()
        self.campo_novo_noBd.raise_()
        self.campo_lista_status_3.raise_()
        self.label_22.raise_()
        self.campo_lista_status_4.raise_()
        self.botao_terminar.raise_()
        self.botao_salvar.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.label_23.raise_()
        self.barra_progresso_pedido.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.botao_consulta_rg.raise_()
        self.campo_cnpj.raise_()
        self.label_18.raise_()
        self.campo_cpf.raise_()
        self.label_10.raise_()
        self.label_14.raise_()
        self.campo_data_nascimento.raise_()
        self.campo_nome.raise_()
        self.botao_dados_cnpj.raise_()
        self.botao_consulta_cnh.raise_()
        self.label_24.raise_()
        self.campo_cnh.raise_()
        self.campo_nome_mae.raise_()
        self.label_6.raise_()
        self.label_15.raise_()
        self.botao_consulta_cpf.raise_()
        self.botao_pasta_cliente.raise_()
        self.campo_email.raise_()
        self.campo_rg.raise_()
        self.label_16.raise_()
        self.campo_seguranca_cnh.raise_()
        self.campo_cnpj_municipio.raise_()
        self.campo_cnpj_uf.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.label_27.raise_()
        self.campo_diretorio_pasta.raise_()
        self.botao_consulta_cnpj.raise_()
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.botao_procurar = QtWidgets.QPushButton(self.tab_6)
        self.botao_procurar.setGeometry(QtCore.QRect(330, 540, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.botao_procurar.setFont(font)
        self.botao_procurar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_procurar.setStyleSheet("border-radius:10px;\n"
"background-color:rgb(73, 218, 107);\n"
"")
        self.botao_procurar.setObjectName("botao_procurar")
        self.label_quantidade_bd = QtWidgets.QLabel(self.tab_6)
        self.label_quantidade_bd.setGeometry(QtCore.QRect(140, 540, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.label_quantidade_bd.setFont(font)
        self.label_quantidade_bd.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_quantidade_bd.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_quantidade_bd.setText("")
        self.label_quantidade_bd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_quantidade_bd.setObjectName("label_quantidade_bd")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_6)
        self.tableWidget.setGeometry(QtCore.QRect(10, 100, 451, 431))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        self.tableWidget.setFont(font)
        self.tableWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.botao_consultar = QtWidgets.QPushButton(self.tab_6)
        self.botao_consultar.setGeometry(QtCore.QRect(420, 30, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.botao_consultar.setFont(font)
        self.botao_consultar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_consultar.setStyleSheet("")
        self.botao_consultar.setObjectName("botao_consultar")
        self.campo_data_ate = QtWidgets.QDateEdit(self.tab_6)
        self.campo_data_ate.setGeometry(QtCore.QRect(130, 30, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.campo_data_ate.setFont(font)
        self.campo_data_ate.setStyleSheet("")
        self.campo_data_ate.setObjectName("campo_data_ate")
        self.campo_lista_status_2 = QtWidgets.QComboBox(self.tab_6)
        self.campo_lista_status_2.setGeometry(QtCore.QRect(250, 30, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.campo_lista_status_2.setFont(font)
        self.campo_lista_status_2.setStyleSheet("")
        self.campo_lista_status_2.setEditable(False)
        self.campo_lista_status_2.setObjectName("campo_lista_status_2")
        self.campo_lista_status_2.addItem("")
        self.campo_lista_status_2.addItem("")
        self.campo_lista_status_2.addItem("")
        self.campo_lista_status_2.addItem("")
        self.campo_lista_status_2.addItem("")
        self.label_19 = QtWidgets.QLabel(self.tab_6)
        self.label_19.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.label_19.setObjectName("label_19")
        self.barra_progresso_consulta = QtWidgets.QProgressBar(self.tab_6)
        self.barra_progresso_consulta.setGeometry(QtCore.QRect(10, 70, 451, 8))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(11)
        self.barra_progresso_consulta.setFont(font)
        self.barra_progresso_consulta.setProperty("value", 0)
        self.barra_progresso_consulta.setAlignment(QtCore.Qt.AlignCenter)
        self.barra_progresso_consulta.setFormat("")
        self.barra_progresso_consulta.setObjectName("barra_progresso_consulta")
        self.label_21 = QtWidgets.QLabel(self.tab_6)
        self.label_21.setGeometry(QtCore.QRect(260, 10, 81, 16))
        self.label_21.setObjectName("label_21")
        self.campo_data_de = QtWidgets.QDateEdit(self.tab_6)
        self.campo_data_de.setGeometry(QtCore.QRect(10, 30, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        self.campo_data_de.setFont(font)
        self.campo_data_de.setStyleSheet("")
        self.campo_data_de.setObjectName("campo_data_de")
        self.label_20 = QtWidgets.QLabel(self.tab_6)
        self.label_20.setGeometry(QtCore.QRect(130, 10, 81, 16))
        self.label_20.setObjectName("label_20")
        self.label_msg_copiado = QtWidgets.QLabel(self.tab_6)
        self.label_msg_copiado.setGeometry(QtCore.QRect(10, 540, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.label_msg_copiado.setFont(font)
        self.label_msg_copiado.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_msg_copiado.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_msg_copiado.setText("")
        self.label_msg_copiado.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_msg_copiado.setObjectName("label_msg_copiado")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 451, 111))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(20, 50, 181, 16))
        self.label_7.setObjectName("label_7")
        self.botao_transf_link_PDF = QtWidgets.QPushButton(self.groupBox_3)
        self.botao_transf_link_PDF.setGeometry(QtCore.QRect(260, 30, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.botao_transf_link_PDF.setFont(font)
        self.botao_transf_link_PDF.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_transf_link_PDF.setObjectName("botao_transf_link_PDF")
        self.campo_link_video = QtWidgets.QLineEdit(self.groupBox_3)
        self.campo_link_video.setGeometry(QtCore.QRect(20, 70, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.campo_link_video.setFont(font)
        self.campo_link_video.setText("")
        self.campo_link_video.setPlaceholderText("")
        self.campo_link_video.setObjectName("campo_link_video")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 130, 451, 301))
        self.groupBox.setObjectName("groupBox")
        self.botao_agrupar_PDF = QtWidgets.QPushButton(self.groupBox)
        self.botao_agrupar_PDF.setGeometry(QtCore.QRect(80, 20, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.botao_agrupar_PDF.setFont(font)
        self.botao_agrupar_PDF.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_agrupar_PDF.setStyleSheet("")
        self.botao_agrupar_PDF.setObjectName("botao_agrupar_PDF")
        self.botao_selecionar_arquivos_mesclar = QtWidgets.QPushButton(self.groupBox)
        self.botao_selecionar_arquivos_mesclar.setGeometry(QtCore.QRect(20, 20, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.botao_selecionar_arquivos_mesclar.setFont(font)
        self.botao_selecionar_arquivos_mesclar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_selecionar_arquivos_mesclar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botao_selecionar_arquivos_mesclar.setStyleSheet("")
        self.botao_selecionar_arquivos_mesclar.setObjectName("botao_selecionar_arquivos_mesclar")
        self.botao_limpar_PDF = QtWidgets.QPushButton(self.groupBox)
        self.botao_limpar_PDF.setGeometry(QtCore.QRect(370, 20, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.botao_limpar_PDF.setFont(font)
        self.botao_limpar_PDF.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_limpar_PDF.setStyleSheet("")
        self.botao_limpar_PDF.setObjectName("botao_limpar_PDF")
        self.barra_progresso_mesclar = QtWidgets.QProgressBar(self.groupBox)
        self.barra_progresso_mesclar.setGeometry(QtCore.QRect(20, 280, 411, 8))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.barra_progresso_mesclar.setFont(font)
        self.barra_progresso_mesclar.setProperty("value", 0)
        self.barra_progresso_mesclar.setAlignment(QtCore.Qt.AlignCenter)
        self.barra_progresso_mesclar.setFormat("")
        self.barra_progresso_mesclar.setObjectName("barra_progresso_mesclar")
        self.label_PDF1 = QtWidgets.QLabel(self.groupBox)
        self.label_PDF1.setGeometry(QtCore.QRect(20, 60, 61, 101))
        self.label_PDF1.setStyleSheet("background-color:rgb(211, 211, 211);")
        self.label_PDF1.setText("")
        self.label_PDF1.setObjectName("label_PDF1")
        self.label_PDF5 = QtWidgets.QLabel(self.groupBox)
        self.label_PDF5.setGeometry(QtCore.QRect(300, 60, 61, 101))
        self.label_PDF5.setStyleSheet("background-color:rgb(211, 211, 211);")
        self.label_PDF5.setText("")
        self.label_PDF5.setObjectName("label_PDF5")
        self.label_PDF4 = QtWidgets.QLabel(self.groupBox)
        self.label_PDF4.setGeometry(QtCore.QRect(230, 60, 61, 101))
        self.label_PDF4.setStyleSheet("background-color:rgb(211, 211, 211);")
        self.label_PDF4.setText("")
        self.label_PDF4.setObjectName("label_PDF4")
        self.label_PDF3 = QtWidgets.QLabel(self.groupBox)
        self.label_PDF3.setGeometry(QtCore.QRect(160, 60, 61, 101))
        self.label_PDF3.setStyleSheet("background-color:rgb(211, 211, 211);")
        self.label_PDF3.setText("")
        self.label_PDF3.setObjectName("label_PDF3")
        self.label_PDF2 = QtWidgets.QLabel(self.groupBox)
        self.label_PDF2.setGeometry(QtCore.QRect(90, 60, 61, 101))
        self.label_PDF2.setStyleSheet("background-color:rgb(211, 211, 211);")
        self.label_PDF2.setText("")
        self.label_PDF2.setObjectName("label_PDF2")
        self.label_PDF6 = QtWidgets.QLabel(self.groupBox)
        self.label_PDF6.setGeometry(QtCore.QRect(370, 60, 61, 101))
        self.label_PDF6.setStyleSheet("background-color:rgb(211, 211, 211);")
        self.label_PDF6.setText("")
        self.label_PDF6.setObjectName("label_PDF6")
        self.label_PDF11 = QtWidgets.QLabel(self.groupBox)
        self.label_PDF11.setGeometry(QtCore.QRect(300, 170, 61, 101))
        self.label_PDF11.setStyleSheet("background-color:rgb(211, 211, 211);")
        self.label_PDF11.setText("")
        self.label_PDF11.setObjectName("label_PDF11")
        self.label_PDF10 = QtWidgets.QLabel(self.groupBox)
        self.label_PDF10.setGeometry(QtCore.QRect(230, 170, 61, 101))
        self.label_PDF10.setStyleSheet("background-color:rgb(211, 211, 211);")
        self.label_PDF10.setText("")
        self.label_PDF10.setObjectName("label_PDF10")
        self.label_PDF7 = QtWidgets.QLabel(self.groupBox)
        self.label_PDF7.setGeometry(QtCore.QRect(20, 170, 61, 101))
        self.label_PDF7.setStyleSheet("background-color:rgb(211, 211, 211);")
        self.label_PDF7.setText("")
        self.label_PDF7.setObjectName("label_PDF7")
        self.label_PDF9 = QtWidgets.QLabel(self.groupBox)
        self.label_PDF9.setGeometry(QtCore.QRect(160, 170, 61, 101))
        self.label_PDF9.setStyleSheet("background-color:rgb(211, 211, 211);")
        self.label_PDF9.setText("")
        self.label_PDF9.setObjectName("label_PDF9")
        self.label_PDF8 = QtWidgets.QLabel(self.groupBox)
        self.label_PDF8.setGeometry(QtCore.QRect(90, 170, 61, 101))
        self.label_PDF8.setStyleSheet("background-color:rgb(211, 211, 211);")
        self.label_PDF8.setText("")
        self.label_PDF8.setObjectName("label_PDF8")
        self.label_PDF12 = QtWidgets.QLabel(self.groupBox)
        self.label_PDF12.setGeometry(QtCore.QRect(370, 170, 61, 101))
        self.label_PDF12.setStyleSheet("background-color:rgb(211, 211, 211);")
        self.label_PDF12.setText("")
        self.label_PDF12.setObjectName("label_PDF12")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 440, 451, 131))
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.botao_converter_jpgPDF = QtWidgets.QPushButton(self.groupBox_2)
        self.botao_converter_jpgPDF.setGeometry(QtCore.QRect(170, 70, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.botao_converter_jpgPDF.setFont(font)
        self.botao_converter_jpgPDF.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_converter_jpgPDF.setStyleSheet("")
        self.botao_converter_jpgPDF.setObjectName("botao_converter_jpgPDF")
        self.barra_progresso_jpg = QtWidgets.QProgressBar(self.groupBox_2)
        self.barra_progresso_jpg.setGeometry(QtCore.QRect(20, 110, 411, 8))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.barra_progresso_jpg.setFont(font)
        self.barra_progresso_jpg.setProperty("value", 0)
        self.barra_progresso_jpg.setAlignment(QtCore.Qt.AlignCenter)
        self.barra_progresso_jpg.setFormat("")
        self.barra_progresso_jpg.setObjectName("barra_progresso_jpg")
        self.pdf_para_jpg = QtWidgets.QRadioButton(self.groupBox_2)
        self.pdf_para_jpg.setGeometry(QtCore.QRect(70, 30, 91, 17))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.pdf_para_jpg.setFont(font)
        self.pdf_para_jpg.setObjectName("pdf_para_jpg")
        self.jpg_para_pdf = QtWidgets.QRadioButton(self.groupBox_2)
        self.jpg_para_pdf.setGeometry(QtCore.QRect(280, 30, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        self.jpg_para_pdf.setFont(font)
        self.jpg_para_pdf.setCheckable(True)
        self.jpg_para_pdf.setChecked(False)
        self.jpg_para_pdf.setObjectName("jpg_para_pdf")
        self.tabWidget.addTab(self.tab, "")
        janela.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(janela)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 475, 21))
        self.menubar.setObjectName("menubar")
        janela.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(janela)
        self.statusbar.setObjectName("statusbar")
        janela.setStatusBar(self.statusbar)

        self.retranslateUi(janela)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(janela)
        janela.setTabOrder(self.campo_pedido, self.campo_data_agendamento)
        janela.setTabOrder(self.campo_data_agendamento, self.campo_hora_agendamento)
        janela.setTabOrder(self.campo_hora_agendamento, self.campo_certificado)
        janela.setTabOrder(self.campo_certificado, self.campo_lista_status_3)
        janela.setTabOrder(self.campo_lista_status_3, self.campo_lista_status_4)
        janela.setTabOrder(self.campo_lista_status_4, self.campo_lista_status)
        janela.setTabOrder(self.campo_lista_status, self.campo_nome)
        janela.setTabOrder(self.campo_nome, self.campo_email)
        janela.setTabOrder(self.campo_email, self.campo_data_nascimento)
        janela.setTabOrder(self.campo_data_nascimento, self.campo_cpf)
        janela.setTabOrder(self.campo_cpf, self.campo_rg)
        janela.setTabOrder(self.campo_rg, self.campo_cnh)
        janela.setTabOrder(self.campo_cnh, self.campo_seguranca_cnh)
        janela.setTabOrder(self.campo_seguranca_cnh, self.campo_nome_mae)
        janela.setTabOrder(self.campo_nome_mae, self.campo_cnpj)
        janela.setTabOrder(self.campo_cnpj, self.campo_diretorio_pasta)
        janela.setTabOrder(self.campo_diretorio_pasta, self.botao_procurar)
        janela.setTabOrder(self.botao_procurar, self.campo_data_ate)
        janela.setTabOrder(self.campo_data_ate, self.botao_terminar)
        janela.setTabOrder(self.botao_terminar, self.campo_link_video)
        janela.setTabOrder(self.campo_link_video, self.botao_consulta_rg)
        janela.setTabOrder(self.botao_consulta_rg, self.botao_salvar)
        janela.setTabOrder(self.botao_salvar, self.botao_selecionar_arquivos_mesclar)
        janela.setTabOrder(self.botao_selecionar_arquivos_mesclar, self.campo_data_de)
        janela.setTabOrder(self.campo_data_de, self.botao_transf_link_PDF)
        janela.setTabOrder(self.botao_transf_link_PDF, self.botao_dados_cnpj)
        janela.setTabOrder(self.botao_dados_cnpj, self.botao_consulta_cnh)
        janela.setTabOrder(self.botao_consulta_cnh, self.botao_converter_jpgPDF)
        janela.setTabOrder(self.botao_converter_jpgPDF, self.campo_lista_status_2)
        janela.setTabOrder(self.campo_lista_status_2, self.tabWidget)
        janela.setTabOrder(self.tabWidget, self.botao_consulta_cpf)
        janela.setTabOrder(self.botao_consulta_cpf, self.botao_pasta_cliente)
        janela.setTabOrder(self.botao_pasta_cliente, self.botao_agrupar_PDF)
        janela.setTabOrder(self.botao_agrupar_PDF, self.botao_limpar_PDF)
        janela.setTabOrder(self.botao_limpar_PDF, self.botao_consultar)
        janela.setTabOrder(self.botao_consultar, self.campo_cnpj_municipio)
        janela.setTabOrder(self.campo_cnpj_municipio, self.campo_cnpj_uf)
        janela.setTabOrder(self.campo_cnpj_uf, self.botao_consulta_cnpj)
        janela.setTabOrder(self.botao_consulta_cnpj, self.tableWidget)

    def retranslateUi(self, janela):
        _translate = QtCore.QCoreApplication.translate
        janela.setWindowTitle(_translate("janela", "MainWindow"))
        self.campo_lista_status.setItemText(0, _translate("janela", "DIGITAÇÃO"))
        self.campo_lista_status.setItemText(1, _translate("janela", "VERIFICAÇÃO"))
        self.campo_lista_status.setItemText(2, _translate("janela", "APROVADO"))
        self.campo_lista_status.setItemText(3, _translate("janela", "CANCELADO"))
        self.label.setText(_translate("janela", "🌟 PEDIDO"))
        self.label_2.setText(_translate("janela", "🌟 TIPO CERTIFICADO"))
        self.label_17.setText(_translate("janela", "🌟 STATUS"))
        self.label_4.setText(_translate("janela", "🌟 HORA AGENDA"))
        self.label_3.setText(_translate("janela", "🌟 DATA AGENDA"))
        self.campo_lista_status_3.setItemText(0, _translate("janela", "NAO"))
        self.campo_lista_status_3.setItemText(1, _translate("janela", "SIM"))
        self.label_22.setText(_translate("janela", "🌟 VENDA?"))
        self.label_23.setText(_translate("janela", "🌟 MODALIDADE"))
        self.campo_lista_status_4.setItemText(1, _translate("janela", "VIDEO"))
        self.campo_lista_status_4.setItemText(2, _translate("janela", "PRESENCIAL"))
        self.botao_terminar.setText(_translate("janela", "FINALIZAR"))
        self.botao_salvar.setText(_translate("janela", "SALVAR"))
        self.label_11.setText(_translate("janela", "e-MAIL"))
        self.label_12.setText(_translate("janela", "NASCIMENTO"))
        self.botao_consulta_rg.setText(_translate("janela", "🔍"))
        self.label_18.setText(_translate("janela", "NOME DA MÃE"))
        self.label_10.setText(_translate("janela", "RG"))
        self.label_14.setText(_translate("janela", "CNPJ"))
        self.botao_dados_cnpj.setText(_translate("janela", "📋"))
        self.botao_consulta_cnh.setText(_translate("janela", "🔍"))
        self.label_24.setText(_translate("janela", "NOME COMPLETO"))
        self.label_6.setText(_translate("janela", "CPF"))
        self.label_15.setText(_translate("janela", "CNH"))
        self.botao_consulta_cpf.setText(_translate("janela", "🔍"))
        self.botao_pasta_cliente.setText(_translate("janela", "📂"))
        self.label_16.setText(_translate("janela", "CÓDIGO DE SEGURANÇA - CNH"))
        self.label_25.setText(_translate("janela", "MUNICÍPIO"))
        self.label_26.setText(_translate("janela", "UF"))
        self.label_27.setText(_translate("janela", "OBSERVAÇÕES"))
        self.botao_consulta_cnpj.setText(_translate("janela", "🔍"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("janela", "Dados pedido"))
        self.botao_procurar.setText(_translate("janela", "EXPORTAR EXCEL"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("janela", "PEDIDO"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("janela", "NOME"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("janela", "DATA"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("janela", "HORA"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("janela", "MODALIDADE"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("janela", "STATUS"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("janela", "VENDA"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("janela", "TIPO"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("janela", "OBSERVAÇÕES"))
        self.botao_consultar.setText(_translate("janela", "🔍"))
        self.campo_lista_status_2.setItemText(0, _translate("janela", "TODAS"))
        self.campo_lista_status_2.setItemText(1, _translate("janela", "DIGITAÇÃO"))
        self.campo_lista_status_2.setItemText(2, _translate("janela", "VERIFICAÇÃO"))
        self.campo_lista_status_2.setItemText(3, _translate("janela", "APROVADO"))
        self.campo_lista_status_2.setItemText(4, _translate("janela", "CANCELADO"))
        self.label_19.setText(_translate("janela", "DE:"))
        self.label_21.setText(_translate("janela", "STATUS"))
        self.label_20.setText(_translate("janela", "ATÉ:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("janela", "Consulta"))
        self.groupBox_3.setTitle(_translate("janela", "TRANSFORMAR  LINK DA VÍDEO-CONFERÊNCIA  EM   PDF"))
        self.label_7.setText(_translate("janela", "TEXTO"))
        self.botao_transf_link_PDF.setText(_translate("janela", "TRANSFORMAR EM PDF"))
        self.groupBox.setTitle(_translate("janela", "MESCLAR PDF - MAX 5 ARQUIVOS"))
        self.botao_agrupar_PDF.setText(_translate("janela", "MESCLAR PDF"))
        self.botao_selecionar_arquivos_mesclar.setText(_translate("janela", "📂"))
        self.botao_limpar_PDF.setText(_translate("janela", "🗑️"))
        self.groupBox_2.setTitle(_translate("janela", "CONVERSOR"))
        self.botao_converter_jpgPDF.setText(_translate("janela", "CONVERTER"))
        self.pdf_para_jpg.setText(_translate("janela", "PDF > JPG"))
        self.jpg_para_pdf.setText(_translate("janela", "JPG > PDF"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("janela", "PDF"))

