
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_janela(object):
    def setupUi(self, janela):
        janela.setObjectName("janela")
        janela.resize(466, 652)
        janela.setWindowFlag(QtCore.Qt.WindowStaysOnTopHint)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        janela.setPalette(palette)
        janela.setFocusPolicy(QtCore.Qt.NoFocus)
        janela.setAutoFillBackground(False)
        janela.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(janela)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(-5, 44, 519, 661))
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777202, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.campo_lista_status = QtWidgets.QComboBox(self.tab_5)
        self.campo_lista_status.setGeometry(QtCore.QRect(290, 125, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.campo_lista_status.setFont(font)
        self.campo_lista_status.setStyleSheet("")
        self.campo_lista_status.setEditable(False)
        self.campo_lista_status.setObjectName("campo_lista_status")
        self.campo_lista_status.addItem("")
        self.campo_lista_status.addItem("")
        self.campo_lista_status.addItem("")
        self.campo_lista_status.addItem("")
        self.label = QtWidgets.QLabel(self.tab_5)
        self.label.setGeometry(QtCore.QRect(10, 10, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_5)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 241, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.campo_data_agendamento = QtWidgets.QDateEdit(self.tab_5)
        self.campo_data_agendamento.setGeometry(QtCore.QRect(230, 25, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.campo_data_agendamento.setFont(font)
        self.campo_data_agendamento.setStyleSheet("")
        self.campo_data_agendamento.setObjectName("campo_data_agendamento")
        self.label_17 = QtWidgets.QLabel(self.tab_5)
        self.label_17.setGeometry(QtCore.QRect(290, 110, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.campo_certificado = QtWidgets.QLineEdit(self.tab_5)
        self.campo_certificado.setGeometry(QtCore.QRect(10, 75, 451, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.campo_certificado.setFont(font)
        self.campo_certificado.setText("")
        self.campo_certificado.setObjectName("campo_certificado")
        self.campo_pedido = QtWidgets.QLineEdit(self.tab_5)
        self.campo_pedido.setGeometry(QtCore.QRect(10, 25, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.campo_pedido.setFont(font)
        self.campo_pedido.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.campo_pedido.setText("")
        self.campo_pedido.setObjectName("campo_pedido")
        self.campo_hora_agendamento = QtWidgets.QTimeEdit(self.tab_5)
        self.campo_hora_agendamento.setGeometry(QtCore.QRect(360, 25, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.campo_hora_agendamento.setFont(font)
        self.campo_hora_agendamento.setStyleSheet("")
        self.campo_hora_agendamento.setObjectName("campo_hora_agendamento")
        self.label_4 = QtWidgets.QLabel(self.tab_5)
        self.label_4.setGeometry(QtCore.QRect(360, 10, 106, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.tab_5)
        self.label_3.setGeometry(QtCore.QRect(230, 9, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.campo_novo_noBd = QtWidgets.QLabel(self.tab_5)
        self.campo_novo_noBd.setGeometry(QtCore.QRect(170, 26, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.campo_novo_noBd.setFont(font)
        self.campo_novo_noBd.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.campo_novo_noBd.setText("")
        self.campo_novo_noBd.setAlignment(QtCore.Qt.AlignCenter)
        self.campo_novo_noBd.setObjectName("campo_novo_noBd")
        self.campo_lista_status_3 = QtWidgets.QComboBox(self.tab_5)
        self.campo_lista_status_3.setGeometry(QtCore.QRect(10, 125, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.campo_lista_status_3.setFont(font)
        self.campo_lista_status_3.setStyleSheet("")
        self.campo_lista_status_3.setEditable(False)
        self.campo_lista_status_3.setObjectName("campo_lista_status_3")
        self.campo_lista_status_3.addItem("")
        self.campo_lista_status_3.addItem("")
        self.label_22 = QtWidgets.QLabel(self.tab_5)
        self.label_22.setGeometry(QtCore.QRect(10, 110, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.tab_5)
        self.label_23.setGeometry(QtCore.QRect(110, 110, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.campo_lista_status_4 = QtWidgets.QComboBox(self.tab_5)
        self.campo_lista_status_4.setGeometry(QtCore.QRect(110, 125, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.campo_lista_status_4.setFont(font)
        self.campo_lista_status_4.setStyleSheet("")
        self.campo_lista_status_4.setEditable(False)
        self.campo_lista_status_4.setObjectName("campo_lista_status_4")
        self.campo_lista_status_4.addItem("")
        self.campo_lista_status_4.setItemText(0, "")
        self.campo_lista_status_4.addItem("")
        self.campo_lista_status_4.addItem("")
        self.barra_progresso_pedido = QtWidgets.QProgressBar(self.tab_5)
        self.barra_progresso_pedido.setGeometry(QtCore.QRect(10, 25, 161, 6))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.barra_progresso_pedido.setFont(font)
        self.barra_progresso_pedido.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.barra_progresso_pedido.setProperty("value", 0)
        self.barra_progresso_pedido.setAlignment(QtCore.Qt.AlignCenter)
        self.barra_progresso_pedido.setFormat("")
        self.barra_progresso_pedido.setObjectName("barra_progresso_pedido")
        self.label_11 = QtWidgets.QLabel(self.tab_5)
        self.label_11.setGeometry(QtCore.QRect(12, 229, 81, 11))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: #333;")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_5)
        self.label_12.setGeometry(QtCore.QRect(330, 227, 121, 13))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: #333;")
        self.label_12.setObjectName("label_12")
        self.botao_consulta_rg = QtWidgets.QPushButton(self.tab_5)
        self.botao_consulta_rg.setGeometry(QtCore.QRect(431, 290, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.botao_consulta_rg.setFont(font)
        self.botao_consulta_rg.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_consulta_rg.setStyleSheet("border-radius:10px;")
        self.botao_consulta_rg.setObjectName("botao_consulta_rg")
        self.campo_cnpj = QtWidgets.QLineEdit(self.tab_5)
        self.campo_cnpj.setGeometry(QtCore.QRect(225, 340, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.campo_cnpj.setFont(font)
        self.campo_cnpj.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.campo_cnpj.setText("")
        self.campo_cnpj.setPlaceholderText("")
        self.campo_cnpj.setObjectName("campo_cnpj")
        self.label_18 = QtWidgets.QLabel(self.tab_5)
        self.label_18.setGeometry(QtCore.QRect(10, 425, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: #333;")
        self.label_18.setObjectName("label_18")
        self.campo_cpf = QtWidgets.QLineEdit(self.tab_5)
        self.campo_cpf.setGeometry(QtCore.QRect(10, 290, 206, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.campo_cpf.setFont(font)
        self.campo_cpf.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.campo_cpf.setText("")
        self.campo_cpf.setPlaceholderText("")
        self.campo_cpf.setObjectName("campo_cpf")
        self.label_10 = QtWidgets.QLabel(self.tab_5)
        self.label_10.setGeometry(QtCore.QRect(225, 280, 81, 11))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: #333;")
        self.label_10.setObjectName("label_10")
        self.label_14 = QtWidgets.QLabel(self.tab_5)
        self.label_14.setGeometry(QtCore.QRect(225, 325, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: #333;")
        self.label_14.setObjectName("label_14")
        self.campo_data_nascimento = QtWidgets.QDateEdit(self.tab_5)
        self.campo_data_nascimento.setGeometry(QtCore.QRect(330, 240, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.campo_data_nascimento.setFont(font)
        self.campo_data_nascimento.setStyleSheet("")
        self.campo_data_nascimento.setObjectName("campo_data_nascimento")
        self.campo_nome = QtWidgets.QLineEdit(self.tab_5)
        self.campo_nome.setGeometry(QtCore.QRect(10, 190, 416, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.campo_nome.setFont(font)
        self.campo_nome.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.campo_nome.setText("")
        self.campo_nome.setPlaceholderText("")
        self.campo_nome.setObjectName("campo_nome")
        self.botao_dados_cnpj = QtWidgets.QPushButton(self.tab_5)
        self.botao_dados_cnpj.setGeometry(QtCore.QRect(430, 340, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.botao_dados_cnpj.setFont(font)
        self.botao_dados_cnpj.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_dados_cnpj.setObjectName("botao_dados_cnpj")
        self.botao_consulta_cnh = QtWidgets.QPushButton(self.tab_5)
        self.botao_consulta_cnh.setGeometry(QtCore.QRect(186, 340, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.botao_consulta_cnh.setFont(font)
        self.botao_consulta_cnh.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_consulta_cnh.setStyleSheet("border-radius:10px;")
        self.botao_consulta_cnh.setObjectName("botao_consulta_cnh")
        self.label_24 = QtWidgets.QLabel(self.tab_5)
        self.label_24.setGeometry(QtCore.QRect(12, 179, 201, 11))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: #333;")
        self.label_24.setObjectName("label_24")
        self.campo_cnh = QtWidgets.QLineEdit(self.tab_5)
        self.campo_cnh.setGeometry(QtCore.QRect(10, 340, 206, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.campo_cnh.setFont(font)
        self.campo_cnh.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.campo_cnh.setText("")
        self.campo_cnh.setObjectName("campo_cnh")
        self.campo_nome_mae = QtWidgets.QLineEdit(self.tab_5)
        self.campo_nome_mae.setGeometry(QtCore.QRect(10, 440, 451, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.campo_nome_mae.setFont(font)
        self.campo_nome_mae.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.campo_nome_mae.setStyleSheet("")
        self.campo_nome_mae.setText("")
        self.campo_nome_mae.setObjectName("campo_nome_mae")
        self.label_6 = QtWidgets.QLabel(self.tab_5)
        self.label_6.setGeometry(QtCore.QRect(10, 275, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: #333;")
        self.label_6.setObjectName("label_6")
        self.label_15 = QtWidgets.QLabel(self.tab_5)
        self.label_15.setGeometry(QtCore.QRect(10, 325, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: #333;")
        self.label_15.setObjectName("label_15")
        self.botao_consulta_cpf = QtWidgets.QPushButton(self.tab_5)
        self.botao_consulta_cpf.setGeometry(QtCore.QRect(186, 290, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.botao_consulta_cpf.setFont(font)
        self.botao_consulta_cpf.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_consulta_cpf.setStyleSheet("border-radius:10px;")
        self.botao_consulta_cpf.setObjectName("botao_consulta_cpf")
        self.botao_pasta_cliente = QtWidgets.QPushButton(self.tab_5)
        self.botao_pasta_cliente.setGeometry(QtCore.QRect(430, 190, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.botao_pasta_cliente.setFont(font)
        self.botao_pasta_cliente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_pasta_cliente.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botao_pasta_cliente.setObjectName("botao_pasta_cliente")
        self.campo_email = QtWidgets.QLineEdit(self.tab_5)
        self.campo_email.setGeometry(QtCore.QRect(10, 240, 316, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.campo_email.setFont(font)
        self.campo_email.setText("")
        self.campo_email.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.campo_email.setPlaceholderText("")
        self.campo_email.setObjectName("campo_email")
        self.campo_rg = QtWidgets.QLineEdit(self.tab_5)
        self.campo_rg.setGeometry(QtCore.QRect(225, 290, 236, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.campo_rg.setFont(font)
        self.campo_rg.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.campo_rg.setPlaceholderText("")
        self.campo_rg.setObjectName("campo_rg")
        self.label_16 = QtWidgets.QLabel(self.tab_5)
        self.label_16.setGeometry(QtCore.QRect(10, 375, 201, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: #333;")
        self.label_16.setObjectName("label_16")
        self.campo_seguranca_cnh = QtWidgets.QLineEdit(self.tab_5)
        self.campo_seguranca_cnh.setGeometry(QtCore.QRect(10, 390, 206, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.campo_seguranca_cnh.setFont(font)
        self.campo_seguranca_cnh.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.campo_seguranca_cnh.setObjectName("campo_seguranca_cnh")
        self.campo_cnpj_municipio = QtWidgets.QLineEdit(self.tab_5)
        self.campo_cnpj_municipio.setEnabled(True)
        self.campo_cnpj_municipio.setGeometry(QtCore.QRect(225, 390, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.campo_cnpj_municipio.setFont(font)
        self.campo_cnpj_municipio.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.campo_cnpj_municipio.setText("")
        self.campo_cnpj_municipio.setPlaceholderText("")
        self.campo_cnpj_municipio.setObjectName("campo_cnpj_municipio")
        self.campo_cnpj_uf = QtWidgets.QLineEdit(self.tab_5)
        self.campo_cnpj_uf.setEnabled(True)
        self.campo_cnpj_uf.setGeometry(QtCore.QRect(395, 390, 66, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.campo_cnpj_uf.setFont(font)
        self.campo_cnpj_uf.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.campo_cnpj_uf.setText("")
        self.campo_cnpj_uf.setPlaceholderText("")
        self.campo_cnpj_uf.setObjectName("campo_cnpj_uf")
        self.label_25 = QtWidgets.QLabel(self.tab_5)
        self.label_25.setGeometry(QtCore.QRect(225, 378, 129, 13))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: #333;")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.tab_5)
        self.label_26.setGeometry(QtCore.QRect(395, 375, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: #333;")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.tab_5)
        self.label_27.setGeometry(QtCore.QRect(12, 477, 131, 13))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color: #333;")
        self.label_27.setObjectName("label_27")
        self.campo_diretorio_pasta = QtWidgets.QTextEdit(self.tab_5)
        self.campo_diretorio_pasta.setGeometry(QtCore.QRect(10, 490, 225, 87))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.campo_diretorio_pasta.setFont(font)
        self.campo_diretorio_pasta.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.campo_diretorio_pasta.setObjectName("campo_diretorio_pasta")
        self.botao_consulta_cnpj = QtWidgets.QPushButton(self.tab_5)
        self.botao_consulta_cnpj.setGeometry(QtCore.QRect(396, 340, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.botao_consulta_cnpj.setFont(font)
        self.botao_consulta_cnpj.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_consulta_cnpj.setStyleSheet("border-radius:10px;")
        self.botao_consulta_cnpj.setObjectName("botao_consulta_cnpj")
        self.line = QtWidgets.QFrame(self.tab_5)
        self.line.setGeometry(QtCore.QRect(-40, 160, 546, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.campo_lista_junta_comercial = QtWidgets.QComboBox(self.tab_5)
        self.campo_lista_junta_comercial.setGeometry(QtCore.QRect(402, 490, 59, 47))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.campo_lista_junta_comercial.setFont(font)
        self.campo_lista_junta_comercial.setStyleSheet("")
        self.campo_lista_junta_comercial.setEditable(False)
        self.campo_lista_junta_comercial.setObjectName("campo_lista_junta_comercial")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.setItemText(0, "")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.botao_junta = QtWidgets.QPushButton(self.tab_5)
        self.botao_junta.setGeometry(QtCore.QRect(402, 540, 59, 37))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.botao_junta.setFont(font)
        self.botao_junta.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_junta.setStyleSheet("")
        self.botao_junta.setObjectName("botao_junta")
        self.label_28 = QtWidgets.QLabel(self.tab_5)
        self.label_28.setGeometry(QtCore.QRect(400, 475, 56, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color: #333;")
        self.label_28.setObjectName("label_28")
        self.campo_lista_documentos = QtWidgets.QTextEdit(self.tab_5)
        self.campo_lista_documentos.setGeometry(QtCore.QRect(242, 490, 155, 87))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.campo_lista_documentos.setFont(font)
        self.campo_lista_documentos.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.campo_lista_documentos.setObjectName("campo_lista_documentos")
        self.label_29 = QtWidgets.QLabel(self.tab_5)
        self.label_29.setGeometry(QtCore.QRect(244, 476, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("color: #333;")
        self.label_29.setObjectName("label_29")
        self.campo_lista_status.raise_()
        self.campo_cnh.raise_()
        self.campo_seguranca_cnh.raise_()
        self.campo_rg.raise_()
        self.campo_data_agendamento.raise_()
        self.label_17.raise_()
        self.campo_certificado.raise_()
        self.campo_pedido.raise_()
        self.campo_hora_agendamento.raise_()
        self.label_4.raise_()
        self.label_3.raise_()
        self.campo_novo_noBd.raise_()
        self.campo_lista_status_3.raise_()
        self.label_22.raise_()
        self.campo_lista_status_4.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.label_23.raise_()
        self.barra_progresso_pedido.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.botao_consulta_rg.raise_()
        self.campo_cnpj.raise_()
        self.label_18.raise_()
        self.campo_cpf.raise_()
        self.label_10.raise_()
        self.label_14.raise_()
        self.campo_data_nascimento.raise_()
        self.campo_nome.raise_()
        self.botao_dados_cnpj.raise_()
        self.botao_consulta_cnh.raise_()
        self.label_24.raise_()
        self.campo_nome_mae.raise_()
        self.label_6.raise_()
        self.label_15.raise_()
        self.botao_consulta_cpf.raise_()
        self.botao_pasta_cliente.raise_()
        self.campo_email.raise_()
        self.label_16.raise_()
        self.campo_cnpj_municipio.raise_()
        self.campo_cnpj_uf.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.label_27.raise_()
        self.campo_diretorio_pasta.raise_()
        self.botao_consulta_cnpj.raise_()
        self.line.raise_()
        self.campo_lista_junta_comercial.raise_()
        self.botao_junta.raise_()
        self.label_28.raise_()
        self.campo_lista_documentos.raise_()
        self.label_29.raise_()
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.botao_procurar = QtWidgets.QPushButton(self.tab_6)
        self.botao_procurar.setGeometry(QtCore.QRect(330, 530, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.botao_procurar.setFont(font)
        self.botao_procurar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_procurar.setStyleSheet("border-radius:10px;\n"
"background-color:rgb(73, 218, 107);\n"
"")
        self.botao_procurar.setObjectName("botao_procurar")
        self.label_quantidade_bd = QtWidgets.QLabel(self.tab_6)
        self.label_quantidade_bd.setGeometry(QtCore.QRect(140, 530, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_quantidade_bd.setFont(font)
        self.label_quantidade_bd.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_quantidade_bd.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_quantidade_bd.setText("")
        self.label_quantidade_bd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_quantidade_bd.setObjectName("label_quantidade_bd")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_6)
        self.tableWidget.setGeometry(QtCore.QRect(10, 85, 451, 439))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget.setFont(font)
        self.tableWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.botao_consultar = QtWidgets.QPushButton(self.tab_6)
        self.botao_consultar.setGeometry(QtCore.QRect(420, 30, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.botao_consultar.setFont(font)
        self.botao_consultar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_consultar.setStyleSheet("")
        self.botao_consultar.setObjectName("botao_consultar")
        self.campo_data_ate = QtWidgets.QDateEdit(self.tab_6)
        self.campo_data_ate.setGeometry(QtCore.QRect(135, 30, 116, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.campo_data_ate.setFont(font)
        self.campo_data_ate.setStyleSheet("")
        self.campo_data_ate.setObjectName("campo_data_ate")
        self.campo_lista_status_2 = QtWidgets.QComboBox(self.tab_6)
        self.campo_lista_status_2.setGeometry(QtCore.QRect(260, 30, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.campo_lista_status_2.setFont(font)
        self.campo_lista_status_2.setStyleSheet("")
        self.campo_lista_status_2.setEditable(False)
        self.campo_lista_status_2.setObjectName("campo_lista_status_2")
        self.campo_lista_status_2.addItem("")
        self.campo_lista_status_2.addItem("")
        self.campo_lista_status_2.addItem("")
        self.campo_lista_status_2.addItem("")
        self.campo_lista_status_2.addItem("")
        self.label_19 = QtWidgets.QLabel(self.tab_6)
        self.label_19.setGeometry(QtCore.QRect(12, 10, 79, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.barra_progresso_consulta = QtWidgets.QProgressBar(self.tab_6)
        self.barra_progresso_consulta.setGeometry(QtCore.QRect(10, 70, 451, 8))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.barra_progresso_consulta.setFont(font)
        self.barra_progresso_consulta.setStyleSheet("color: rgb(90,54,247);")
        self.barra_progresso_consulta.setProperty("value", 0)
        self.barra_progresso_consulta.setAlignment(QtCore.Qt.AlignCenter)
        self.barra_progresso_consulta.setFormat("")
        self.barra_progresso_consulta.setObjectName("barra_progresso_consulta")
        self.label_21 = QtWidgets.QLabel(self.tab_6)
        self.label_21.setGeometry(QtCore.QRect(265, 10, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.campo_data_de = QtWidgets.QDateEdit(self.tab_6)
        self.campo_data_de.setGeometry(QtCore.QRect(10, 30, 116, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.campo_data_de.setFont(font)
        self.campo_data_de.setStyleSheet("")
        self.campo_data_de.setObjectName("campo_data_de")
        self.label_20 = QtWidgets.QLabel(self.tab_6)
        self.label_20.setGeometry(QtCore.QRect(140, 10, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_msg_copiado = QtWidgets.QLabel(self.tab_6)
        self.label_msg_copiado.setGeometry(QtCore.QRect(10, 530, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_msg_copiado.setFont(font)
        self.label_msg_copiado.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_msg_copiado.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_msg_copiado.setText("")
        self.label_msg_copiado.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_msg_copiado.setObjectName("label_msg_copiado")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.campo_msg1 = QtWidgets.QTextEdit(self.tab_2)
        self.campo_msg1.setGeometry(QtCore.QRect(10, 20, 451, 96))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.campo_msg1.setFont(font)
        self.campo_msg1.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.campo_msg1.setStyleSheet("border: 2px solid #031525;\n"
"")
        self.campo_msg1.setObjectName("campo_msg1")
        self.campo_msg3 = QtWidgets.QTextEdit(self.tab_2)
        self.campo_msg3.setGeometry(QtCore.QRect(10, 210, 451, 36))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.campo_msg3.setFont(font)
        self.campo_msg3.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.campo_msg3.setStyleSheet("border: 2px solid #031525;\n"
"")
        self.campo_msg3.setObjectName("campo_msg3")
        self.campo_msg7 = QtWidgets.QTextEdit(self.tab_2)
        self.campo_msg7.setGeometry(QtCore.QRect(10, 440, 451, 61))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.campo_msg7.setFont(font)
        self.campo_msg7.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.campo_msg7.setStyleSheet("border: 2px solid #031525;\n"
"")
        self.campo_msg7.setObjectName("campo_msg7")
        self.campo_msg2 = QtWidgets.QTextEdit(self.tab_2)
        self.campo_msg2.setGeometry(QtCore.QRect(10, 130, 451, 61))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.campo_msg2.setFont(font)
        self.campo_msg2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.campo_msg2.setStyleSheet("border: 2px solid #031525;\n"
"")
        self.campo_msg2.setObjectName("campo_msg2")
        self.campo_msg6 = QtWidgets.QTextEdit(self.tab_2)
        self.campo_msg6.setGeometry(QtCore.QRect(10, 380, 451, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.campo_msg6.setFont(font)
        self.campo_msg6.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.campo_msg6.setStyleSheet("border: 2px solid #031525;\n"
"")
        self.campo_msg6.setObjectName("campo_msg6")
        self.campo_msg4 = QtWidgets.QTextEdit(self.tab_2)
        self.campo_msg4.setGeometry(QtCore.QRect(10, 260, 451, 36))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.campo_msg4.setFont(font)
        self.campo_msg4.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.campo_msg4.setStyleSheet("border: 2px solid #031525;\n"
"")
        self.campo_msg4.setObjectName("campo_msg4")
        self.campo_msg5 = QtWidgets.QTextEdit(self.tab_2)
        self.campo_msg5.setGeometry(QtCore.QRect(10, 310, 451, 51))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.campo_msg5.setFont(font)
        self.campo_msg5.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.campo_msg5.setStyleSheet("border: 2px solid #031525;\n"
"")
        self.campo_msg5.setObjectName("campo_msg5")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.caminho_pasta = QtWidgets.QLineEdit(self.tab)
        self.caminho_pasta.setEnabled(True)
        self.caminho_pasta.setGeometry(QtCore.QRect(10, 90, 451, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.caminho_pasta.setFont(font)
        self.caminho_pasta.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.caminho_pasta.setStyleSheet("")
        self.caminho_pasta.setText("")
        self.caminho_pasta.setObjectName("caminho_pasta")
        self.campo_verifica_tela_cheia = QtWidgets.QLineEdit(self.tab)
        self.campo_verifica_tela_cheia.setEnabled(True)
        self.campo_verifica_tela_cheia.setGeometry(QtCore.QRect(9, 146, 159, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.campo_verifica_tela_cheia.setFont(font)
        self.campo_verifica_tela_cheia.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.campo_verifica_tela_cheia.setStyleSheet("")
        self.campo_verifica_tela_cheia.setText("")
        self.campo_verifica_tela_cheia.setObjectName("campo_verifica_tela_cheia")
        self.caminho_pasta_principal = QtWidgets.QLineEdit(self.tab)
        self.caminho_pasta_principal.setEnabled(True)
        self.caminho_pasta_principal.setGeometry(QtCore.QRect(10, 30, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.caminho_pasta_principal.setFont(font)
        self.caminho_pasta_principal.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.caminho_pasta_principal.setStyleSheet("")
        self.caminho_pasta_principal.setText("")
        self.caminho_pasta_principal.setObjectName("caminho_pasta_principal")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setGeometry(QtCore.QRect(14, 17, 181, 13))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setGeometry(QtCore.QRect(12, 76, 181, 13))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.tab)
        self.label_9.setGeometry(QtCore.QRect(10, 133, 67, 13))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(7)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.botao_altera_pasta_principal = QtWidgets.QPushButton(self.tab)
        self.botao_altera_pasta_principal.setGeometry(QtCore.QRect(430, 30, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.botao_altera_pasta_principal.setFont(font)
        self.botao_altera_pasta_principal.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_altera_pasta_principal.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botao_altera_pasta_principal.setObjectName("botao_altera_pasta_principal")
        self.tabWidget.addTab(self.tab, "")
        self.botao_print_direto_na_pasta = QtWidgets.QPushButton(self.centralwidget)
        self.botao_print_direto_na_pasta.setGeometry(QtCore.QRect(55, -10, 47, 55))
        font = QtGui.QFont()
        font.setPointSize(26)
        self.botao_print_direto_na_pasta.setFont(font)
        self.botao_print_direto_na_pasta.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_print_direto_na_pasta.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.botao_print_direto_na_pasta.setStyleSheet("border-radius:10px;")
        self.botao_print_direto_na_pasta.setFlat(True)
        self.botao_print_direto_na_pasta.setObjectName("botao_print_direto_na_pasta")
        self.botao_gerar_link = QtWidgets.QPushButton(self.centralwidget)
        self.botao_gerar_link.setGeometry(QtCore.QRect(110, 0, 41, 39))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.botao_gerar_link.setFont(font)
        self.botao_gerar_link.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_gerar_link.setStyleSheet("border-radius:10px;")
        self.botao_gerar_link.setFlat(True)
        self.botao_gerar_link.setObjectName("botao_gerar_link")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(-15, -5, 496, 51))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color:rgb(90,54,247);\n"
"")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.botao_tela_cheia = QtWidgets.QPushButton(self.centralwidget)
        self.botao_tela_cheia.setGeometry(QtCore.QRect(5, 0, 46, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.botao_tela_cheia.setFont(font)
        self.botao_tela_cheia.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_tela_cheia.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.botao_tela_cheia.setStyleSheet("border-radius:10px;")
        self.botao_tela_cheia.setFlat(True)
        self.botao_tela_cheia.setObjectName("botao_tela_cheia")
        self.botao_salvar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_salvar.setGeometry(QtCore.QRect(310, 0, 46, 43))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.botao_salvar.setFont(font)
        self.botao_salvar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_salvar.setStyleSheet("border-radius:10px;\n"
"\n"
"")
        self.botao_salvar.setFlat(True)
        self.botao_salvar.setObjectName("botao_salvar")
        self.botao_terminar = QtWidgets.QPushButton(self.centralwidget)
        self.botao_terminar.setGeometry(QtCore.QRect(360, 9, 96, 29))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.botao_terminar.setFont(font)
        self.botao_terminar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_terminar.setStyleSheet("border-radius:10px;\n"
"background-color:rgb(73, 218, 107);\n"
"color:rgb(90,54,247);\n"
"")
        self.botao_terminar.setFlat(True)
        self.botao_terminar.setObjectName("botao_terminar")
        self.botao_agrupar_PDF = QtWidgets.QPushButton(self.centralwidget)
        self.botao_agrupar_PDF.setGeometry(QtCore.QRect(202, 0, 55, 39))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(23)
        font.setBold(False)
        font.setWeight(50)
        self.botao_agrupar_PDF.setFont(font)
        self.botao_agrupar_PDF.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_agrupar_PDF.setStyleSheet("border-radius:10px;")
        self.botao_agrupar_PDF.setFlat(True)
        self.botao_agrupar_PDF.setObjectName("botao_agrupar_PDF")
        self.botao_converter_todas_imagens_em_pdf = QtWidgets.QPushButton(self.centralwidget)
        self.botao_converter_todas_imagens_em_pdf.setGeometry(QtCore.QRect(154, 4, 47, 33))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.botao_converter_todas_imagens_em_pdf.setFont(font)
        self.botao_converter_todas_imagens_em_pdf.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_converter_todas_imagens_em_pdf.setStyleSheet("border-radius:10px;")
        self.botao_converter_todas_imagens_em_pdf.setAutoDefault(False)
        self.botao_converter_todas_imagens_em_pdf.setDefault(False)
        self.botao_converter_todas_imagens_em_pdf.setFlat(True)
        self.botao_converter_todas_imagens_em_pdf.setObjectName("botao_converter_todas_imagens_em_pdf")
        self.label_5.raise_()
        self.tabWidget.raise_()
        self.botao_print_direto_na_pasta.raise_()
        self.botao_gerar_link.raise_()
        self.botao_tela_cheia.raise_()
        self.botao_salvar.raise_()
        self.botao_terminar.raise_()
        self.botao_agrupar_PDF.raise_()
        self.botao_converter_todas_imagens_em_pdf.raise_()
        janela.setCentralWidget(self.centralwidget)

        self.retranslateUi(janela)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(janela)
        janela.setTabOrder(self.campo_pedido, self.campo_data_agendamento)
        janela.setTabOrder(self.campo_data_agendamento, self.campo_hora_agendamento)
        janela.setTabOrder(self.campo_hora_agendamento, self.campo_certificado)
        janela.setTabOrder(self.campo_certificado, self.campo_lista_status_3)
        janela.setTabOrder(self.campo_lista_status_3, self.campo_lista_status_4)
        janela.setTabOrder(self.campo_lista_status_4, self.campo_lista_status)
        janela.setTabOrder(self.campo_lista_status, self.campo_nome)
        janela.setTabOrder(self.campo_nome, self.campo_email)
        janela.setTabOrder(self.campo_email, self.campo_data_nascimento)
        janela.setTabOrder(self.campo_data_nascimento, self.campo_cpf)
        janela.setTabOrder(self.campo_cpf, self.campo_rg)
        janela.setTabOrder(self.campo_rg, self.campo_cnh)
        janela.setTabOrder(self.campo_cnh, self.campo_cnpj)
        janela.setTabOrder(self.campo_cnpj, self.campo_seguranca_cnh)
        janela.setTabOrder(self.campo_seguranca_cnh, self.campo_nome_mae)
        janela.setTabOrder(self.campo_nome_mae, self.campo_diretorio_pasta)
        janela.setTabOrder(self.campo_diretorio_pasta, self.botao_procurar)
        janela.setTabOrder(self.botao_procurar, self.campo_data_ate)
        janela.setTabOrder(self.campo_data_ate, self.botao_terminar)
        janela.setTabOrder(self.botao_terminar, self.botao_consulta_rg)
        janela.setTabOrder(self.botao_consulta_rg, self.botao_salvar)
        janela.setTabOrder(self.botao_salvar, self.campo_data_de)
        janela.setTabOrder(self.campo_data_de, self.botao_dados_cnpj)
        janela.setTabOrder(self.botao_dados_cnpj, self.botao_consulta_cnh)
        janela.setTabOrder(self.botao_consulta_cnh, self.campo_lista_status_2)
        janela.setTabOrder(self.campo_lista_status_2, self.tabWidget)
        janela.setTabOrder(self.tabWidget, self.botao_consulta_cpf)
        janela.setTabOrder(self.botao_consulta_cpf, self.botao_pasta_cliente)
        janela.setTabOrder(self.botao_pasta_cliente, self.botao_consultar)
        janela.setTabOrder(self.botao_consultar, self.campo_cnpj_municipio)
        janela.setTabOrder(self.campo_cnpj_municipio, self.campo_cnpj_uf)
        janela.setTabOrder(self.campo_cnpj_uf, self.botao_consulta_cnpj)
        janela.setTabOrder(self.botao_consulta_cnpj, self.tableWidget)

    def retranslateUi(self, janela):
        _translate = QtCore.QCoreApplication.translate
        janela.setWindowTitle(_translate("janela", "MainWindow"))
        self.campo_lista_status.setItemText(0, _translate("janela", "DIGITAÇÃO"))
        self.campo_lista_status.setItemText(1, _translate("janela", "VERIFICAÇÃO"))
        self.campo_lista_status.setItemText(2, _translate("janela", "APROVADO"))
        self.campo_lista_status.setItemText(3, _translate("janela", "CANCELADO"))
        self.label.setText(_translate("janela", "🌟 PEDIDO"))
        self.label_2.setText(_translate("janela", "🌟 TIPO CERTIFICADO"))
        self.label_17.setText(_translate("janela", "🌟 STATUS"))
        self.label_4.setText(_translate("janela", "🌟 HORA AGENDA"))
        self.label_3.setText(_translate("janela", "🌟 DATA AGENDA"))
        self.campo_lista_status_3.setItemText(0, _translate("janela", "NAO"))
        self.campo_lista_status_3.setItemText(1, _translate("janela", "SIM"))
        self.label_22.setText(_translate("janela", "🌟 VENDA?"))
        self.label_23.setText(_translate("janela", "🌟 MODALIDADE"))
        self.campo_lista_status_4.setItemText(1, _translate("janela", "VIDEO"))
        self.campo_lista_status_4.setItemText(2, _translate("janela", "PRESENCIAL"))
        self.label_11.setText(_translate("janela", "e-MAIL"))
        self.label_12.setText(_translate("janela", "NASCIMENTO"))
        self.botao_consulta_rg.setText(_translate("janela", "🔍"))
        self.label_18.setText(_translate("janela", "NOME DA MÃE"))
        self.label_10.setText(_translate("janela", "RG"))
        self.label_14.setText(_translate("janela", "CNPJ"))
        self.botao_dados_cnpj.setText(_translate("janela", "📋"))
        self.botao_consulta_cnh.setText(_translate("janela", "🔍"))
        self.label_24.setText(_translate("janela", "NOME COMPLETO"))
        self.label_6.setText(_translate("janela", "CPF"))
        self.label_15.setText(_translate("janela", "CNH"))
        self.botao_consulta_cpf.setText(_translate("janela", "🔍︎"))
        self.botao_pasta_cliente.setText(_translate("janela", "📂"))
        self.label_16.setText(_translate("janela", "CÓDIGO DE SEGURANÇA - CNH"))
        self.label_25.setText(_translate("janela", "MUNICÍPIO CNPJ"))
        self.label_26.setText(_translate("janela", "UF"))
        self.label_27.setText(_translate("janela", "OBSERVAÇÕES"))
        self.botao_consulta_cnpj.setText(_translate("janela", "🔍"))
        self.campo_lista_junta_comercial.setItemText(1, _translate("janela", "AC"))
        self.campo_lista_junta_comercial.setItemText(2, _translate("janela", "AL"))
        self.campo_lista_junta_comercial.setItemText(3, _translate("janela", "AM"))
        self.campo_lista_junta_comercial.setItemText(4, _translate("janela", "AP"))
        self.campo_lista_junta_comercial.setItemText(5, _translate("janela", "BA"))
        self.campo_lista_junta_comercial.setItemText(6, _translate("janela", "CE"))
        self.campo_lista_junta_comercial.setItemText(7, _translate("janela", "DF"))
        self.campo_lista_junta_comercial.setItemText(8, _translate("janela", "ES"))
        self.campo_lista_junta_comercial.setItemText(9, _translate("janela", "GO"))
        self.campo_lista_junta_comercial.setItemText(10, _translate("janela", "MA"))
        self.campo_lista_junta_comercial.setItemText(11, _translate("janela", "MG"))
        self.campo_lista_junta_comercial.setItemText(12, _translate("janela", "MS"))
        self.campo_lista_junta_comercial.setItemText(13, _translate("janela", "MT"))
        self.campo_lista_junta_comercial.setItemText(14, _translate("janela", "PA"))
        self.campo_lista_junta_comercial.setItemText(15, _translate("janela", "PB"))
        self.campo_lista_junta_comercial.setItemText(16, _translate("janela", "PE"))
        self.campo_lista_junta_comercial.setItemText(17, _translate("janela", "PI"))
        self.campo_lista_junta_comercial.setItemText(18, _translate("janela", "PR"))
        self.campo_lista_junta_comercial.setItemText(19, _translate("janela", "RJ"))
        self.campo_lista_junta_comercial.setItemText(20, _translate("janela", "RN"))
        self.campo_lista_junta_comercial.setItemText(21, _translate("janela", "RO"))
        self.campo_lista_junta_comercial.setItemText(22, _translate("janela", "RR"))
        self.campo_lista_junta_comercial.setItemText(23, _translate("janela", "RS"))
        self.campo_lista_junta_comercial.setItemText(24, _translate("janela", "SC"))
        self.campo_lista_junta_comercial.setItemText(25, _translate("janela", "SE"))
        self.campo_lista_junta_comercial.setItemText(26, _translate("janela", "SP"))
        self.campo_lista_junta_comercial.setItemText(27, _translate("janela", "TO"))
        self.botao_junta.setText(_translate("janela", "IR"))
        self.label_28.setText(_translate("janela", "JUNTA C.."))
        self.label_29.setText(_translate("janela", "DOCUMENTOS NA PASTA"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("janela", "Dados pedido"))
        self.botao_procurar.setText(_translate("janela", "EXPORTAR EXCEL"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("janela", "PEDIDO"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("janela", "NOME"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("janela", "DATA"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("janela", "HORA"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("janela", "MODALIDADE"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("janela", "STATUS"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("janela", "VENDA"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("janela", "TIPO"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("janela", "OBSERVAÇÕES"))
        self.botao_consultar.setText(_translate("janela", "🔍"))
        self.campo_lista_status_2.setItemText(0, _translate("janela", "TODAS"))
        self.campo_lista_status_2.setItemText(1, _translate("janela", "DIGITAÇÃO"))
        self.campo_lista_status_2.setItemText(2, _translate("janela", "VERIFICAÇÃO"))
        self.campo_lista_status_2.setItemText(3, _translate("janela", "APROVADO"))
        self.campo_lista_status_2.setItemText(4, _translate("janela", "CANCELADO"))
        self.label_19.setText(_translate("janela", "DE:"))
        self.label_21.setText(_translate("janela", "STATUS"))
        self.label_20.setText(_translate("janela", "ATÉ:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("janela", "Consulta"))
        self.campo_msg1.setHtml(_translate("janela", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Helvetica\',\'Helvetica\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Olá! tudo bem?</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Preciso de uma foto completa do seu documento de identificação,podendo ser (CNH, RG, OAB),<span style=\" font-weight:600;\"> FRENTE E VERSO</span>.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">--Por favor, retire o documento do plástico e abra-o. </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">--O VERSO é a parte que contém o QR code.</p></body></html>"))
        self.campo_msg3.setHtml(_translate("janela", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Helvetica\',\'Helvetica\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">O senhor é o responsável legal pela empresa perante a Receita Federal?</p></body></html>"))
        self.campo_msg7.setHtml(_translate("janela", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Helvetica\',\'Helvetica\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Agradeço pela disponibilidade. Se precisar adquirir mais certificados, pode fazê-lo através do link: <a href=\"https://loja.certisign.com.br/?cod_rev=91384\"><span style=\" font-weight:600; text-decoration: underline; color:#0000ff;\">https://loja.certisign.com.br/?cod_rev=91384</span></a>. Até mais!</p></body></html>"))
        self.campo_msg2.setHtml(_translate("janela", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Helvetica\',\'Helvetica\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Irei precisar também do documento de constituição da empresa, podendo ser o<span style=\" font-weight:600;\"> Contrato Social, Certidão de inteiro teor ,Estatuto social,Requerimento de empresário.</span></p></body></html>"))
        self.campo_msg6.setHtml(_translate("janela", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Helvetica\',\'Helvetica\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Podemos iniciar a vídeo-conferência?</p></body></html>"))
        self.campo_msg4.setHtml(_translate("janela", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Helvetica\',\'Helvetica\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Deseja adicionar o número do PIS/CEI ao seu certificado?</p></body></html>"))
        self.campo_msg5.setHtml(_translate("janela", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Helvetica\',\'Helvetica\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Helvetica\';\">Estou finalizando o chat devido à ausência de interação. Se precisar de ajuda posteriormente, estou à disposição no Whatsapp (11) 97187-2108. Até mais!</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("janela", "Script"))
        self.label_7.setText(_translate("janela", "DIRETÓRIO PASTA PRINCIPAL"))
        self.label_8.setText(_translate("janela", "DIRETÓRIO PASTA CLIENTE ATUAL"))
        self.label_9.setText(_translate("janela", "TELA CHEIA"))
        self.botao_altera_pasta_principal.setText(_translate("janela", "📂"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("janela", "Configs"))
        self.botao_print_direto_na_pasta.setText(_translate("janela", "📸"))
        self.botao_gerar_link.setText(_translate("janela", "🔗"))
        self.botao_tela_cheia.setText(_translate("janela", "🔓"))
        self.botao_salvar.setText(_translate("janela", "💾"))
        self.botao_terminar.setText(_translate("janela", "FINALIZAR"))
        self.botao_agrupar_PDF.setText(_translate("janela", "🗃️"))
        self.botao_converter_todas_imagens_em_pdf.setText(_translate("janela", "🔄️"))


