
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_janela(object):
    def setupUi(self, janela):
        janela.setObjectName("janela")
        janela.resize(474, 597)
        janela.setWindowFlag(QtCore.Qt.WindowStaysOnTopHint)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 120, 215))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        janela.setPalette(palette)
        janela.setFocusPolicy(QtCore.Qt.NoFocus)
        janela.setAutoFillBackground(False)
        janela.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(janela)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 473, 595))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777202, 16777215))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.campo_lista_status = QtWidgets.QComboBox(self.tab_5)
        self.campo_lista_status.setGeometry(QtCore.QRect(290, 125, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.campo_lista_status.setFont(font)
        self.campo_lista_status.setStyleSheet("")
        self.campo_lista_status.setEditable(False)
        self.campo_lista_status.setObjectName("campo_lista_status")
        self.campo_lista_status.addItem("")
        self.campo_lista_status.addItem("")
        self.campo_lista_status.addItem("")
        self.campo_lista_status.addItem("")
        self.label = QtWidgets.QLabel(self.tab_5)
        self.label.setGeometry(QtCore.QRect(10, 5, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_5)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 241, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.campo_data_agendamento = QtWidgets.QDateEdit(self.tab_5)
        self.campo_data_agendamento.setGeometry(QtCore.QRect(230, 25, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.campo_data_agendamento.setFont(font)
        self.campo_data_agendamento.setStyleSheet("")
        self.campo_data_agendamento.setObjectName("campo_data_agendamento")
        self.label_17 = QtWidgets.QLabel(self.tab_5)
        self.label_17.setGeometry(QtCore.QRect(290, 110, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.campo_certificado = QtWidgets.QLineEdit(self.tab_5)
        self.campo_certificado.setGeometry(QtCore.QRect(10, 75, 451, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.campo_certificado.setFont(font)
        self.campo_certificado.setText("")
        self.campo_certificado.setObjectName("campo_certificado")
        self.campo_pedido = QtWidgets.QLineEdit(self.tab_5)
        self.campo_pedido.setGeometry(QtCore.QRect(10, 25, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.campo_pedido.setFont(font)
        self.campo_pedido.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.campo_pedido.setText("")
        self.campo_pedido.setObjectName("campo_pedido")
        self.campo_hora_agendamento = QtWidgets.QTimeEdit(self.tab_5)
        self.campo_hora_agendamento.setGeometry(QtCore.QRect(360, 25, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.campo_hora_agendamento.setFont(font)
        self.campo_hora_agendamento.setStyleSheet("")
        self.campo_hora_agendamento.setObjectName("campo_hora_agendamento")
        self.label_4 = QtWidgets.QLabel(self.tab_5)
        self.label_4.setGeometry(QtCore.QRect(355, 5, 106, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.tab_5)
        self.label_3.setGeometry(QtCore.QRect(230, 5, 101, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.campo_novo_noBd = QtWidgets.QLabel(self.tab_5)
        self.campo_novo_noBd.setGeometry(QtCore.QRect(180, 25, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.campo_novo_noBd.setFont(font)
        self.campo_novo_noBd.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.campo_novo_noBd.setText("")
        self.campo_novo_noBd.setAlignment(QtCore.Qt.AlignCenter)
        self.campo_novo_noBd.setObjectName("campo_novo_noBd")
        self.campo_lista_status_3 = QtWidgets.QComboBox(self.tab_5)
        self.campo_lista_status_3.setGeometry(QtCore.QRect(10, 125, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.campo_lista_status_3.setFont(font)
        self.campo_lista_status_3.setStyleSheet("")
        self.campo_lista_status_3.setEditable(False)
        self.campo_lista_status_3.setObjectName("campo_lista_status_3")
        self.campo_lista_status_3.addItem("")
        self.campo_lista_status_3.addItem("")
        self.label_22 = QtWidgets.QLabel(self.tab_5)
        self.label_22.setGeometry(QtCore.QRect(10, 110, 111, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.tab_5)
        self.label_23.setGeometry(QtCore.QRect(110, 110, 101, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.campo_lista_status_4 = QtWidgets.QComboBox(self.tab_5)
        self.campo_lista_status_4.setGeometry(QtCore.QRect(110, 125, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.campo_lista_status_4.setFont(font)
        self.campo_lista_status_4.setStyleSheet("")
        self.campo_lista_status_4.setEditable(False)
        self.campo_lista_status_4.setObjectName("campo_lista_status_4")
        self.campo_lista_status_4.addItem("")
        self.campo_lista_status_4.setItemText(0, "")
        self.campo_lista_status_4.addItem("")
        self.campo_lista_status_4.addItem("")
        self.botao_terminar = QtWidgets.QPushButton(self.tab_5)
        self.botao_terminar.setGeometry(QtCore.QRect(350, 530, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.botao_terminar.setFont(font)
        self.botao_terminar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_terminar.setStyleSheet("border-radius:10px;\n"
"background-color:rgb(73, 218, 107);")
        self.botao_terminar.setObjectName("botao_terminar")
        self.botao_salvar = QtWidgets.QPushButton(self.tab_5)
        self.botao_salvar.setGeometry(QtCore.QRect(350, 490, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.botao_salvar.setFont(font)
        self.botao_salvar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_salvar.setStyleSheet("border-radius:10px;\n"
"background-color:rgb(0, 180, 210);\n"
"\n"
"")
        self.botao_salvar.setObjectName("botao_salvar")
        self.barra_progresso_pedido = QtWidgets.QProgressBar(self.tab_5)
        self.barra_progresso_pedido.setGeometry(QtCore.QRect(10, 25, 161, 6))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.barra_progresso_pedido.setFont(font)
        self.barra_progresso_pedido.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.barra_progresso_pedido.setProperty("value", 0)
        self.barra_progresso_pedido.setAlignment(QtCore.Qt.AlignCenter)
        self.barra_progresso_pedido.setFormat("")
        self.barra_progresso_pedido.setObjectName("barra_progresso_pedido")
        self.label_11 = QtWidgets.QLabel(self.tab_5)
        self.label_11.setGeometry(QtCore.QRect(12, 224, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: #333;")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_5)
        self.label_12.setGeometry(QtCore.QRect(340, 224, 121, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: #333;")
        self.label_12.setObjectName("label_12")
        self.botao_consulta_rg = QtWidgets.QPushButton(self.tab_5)
        self.botao_consulta_rg.setGeometry(QtCore.QRect(431, 290, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.botao_consulta_rg.setFont(font)
        self.botao_consulta_rg.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_consulta_rg.setStyleSheet("border-radius:10px;")
        self.botao_consulta_rg.setObjectName("botao_consulta_rg")
        self.campo_cnpj = QtWidgets.QLineEdit(self.tab_5)
        self.campo_cnpj.setGeometry(QtCore.QRect(225, 340, 201, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.campo_cnpj.setFont(font)
        self.campo_cnpj.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.campo_cnpj.setText("")
        self.campo_cnpj.setPlaceholderText("")
        self.campo_cnpj.setObjectName("campo_cnpj")
        self.label_18 = QtWidgets.QLabel(self.tab_5)
        self.label_18.setGeometry(QtCore.QRect(10, 425, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: #333;")
        self.label_18.setObjectName("label_18")
        self.campo_cpf = QtWidgets.QLineEdit(self.tab_5)
        self.campo_cpf.setGeometry(QtCore.QRect(10, 290, 206, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.campo_cpf.setFont(font)
        self.campo_cpf.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.campo_cpf.setText("")
        self.campo_cpf.setPlaceholderText("")
        self.campo_cpf.setObjectName("campo_cpf")
        self.label_10 = QtWidgets.QLabel(self.tab_5)
        self.label_10.setGeometry(QtCore.QRect(225, 275, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: #333;")
        self.label_10.setObjectName("label_10")
        self.label_14 = QtWidgets.QLabel(self.tab_5)
        self.label_14.setGeometry(QtCore.QRect(225, 325, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: #333;")
        self.label_14.setObjectName("label_14")
        self.campo_data_nascimento = QtWidgets.QDateEdit(self.tab_5)
        self.campo_data_nascimento.setGeometry(QtCore.QRect(330, 240, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.campo_data_nascimento.setFont(font)
        self.campo_data_nascimento.setStyleSheet("")
        self.campo_data_nascimento.setObjectName("campo_data_nascimento")
        self.campo_nome = QtWidgets.QLineEdit(self.tab_5)
        self.campo_nome.setGeometry(QtCore.QRect(10, 190, 416, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.campo_nome.setFont(font)
        self.campo_nome.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.campo_nome.setText("")
        self.campo_nome.setPlaceholderText("")
        self.campo_nome.setObjectName("campo_nome")
        self.botao_dados_cnpj = QtWidgets.QPushButton(self.tab_5)
        self.botao_dados_cnpj.setGeometry(QtCore.QRect(430, 340, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.botao_dados_cnpj.setFont(font)
        self.botao_dados_cnpj.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_dados_cnpj.setObjectName("botao_dados_cnpj")
        self.botao_consulta_cnh = QtWidgets.QPushButton(self.tab_5)
        self.botao_consulta_cnh.setGeometry(QtCore.QRect(186, 340, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.botao_consulta_cnh.setFont(font)
        self.botao_consulta_cnh.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_consulta_cnh.setStyleSheet("border-radius:10px;")
        self.botao_consulta_cnh.setObjectName("botao_consulta_cnh")
        self.label_24 = QtWidgets.QLabel(self.tab_5)
        self.label_24.setGeometry(QtCore.QRect(12, 174, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet("color: #333;")
        self.label_24.setObjectName("label_24")
        self.campo_cnh = QtWidgets.QLineEdit(self.tab_5)
        self.campo_cnh.setGeometry(QtCore.QRect(10, 340, 206, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.campo_cnh.setFont(font)
        self.campo_cnh.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.campo_cnh.setText("")
        self.campo_cnh.setObjectName("campo_cnh")
        self.campo_nome_mae = QtWidgets.QLineEdit(self.tab_5)
        self.campo_nome_mae.setGeometry(QtCore.QRect(10, 440, 451, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.campo_nome_mae.setFont(font)
        self.campo_nome_mae.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.campo_nome_mae.setStyleSheet("")
        self.campo_nome_mae.setText("")
        self.campo_nome_mae.setObjectName("campo_nome_mae")
        self.label_6 = QtWidgets.QLabel(self.tab_5)
        self.label_6.setGeometry(QtCore.QRect(10, 275, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: #333;")
        self.label_6.setObjectName("label_6")
        self.label_15 = QtWidgets.QLabel(self.tab_5)
        self.label_15.setGeometry(QtCore.QRect(10, 325, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: #333;")
        self.label_15.setObjectName("label_15")
        self.botao_consulta_cpf = QtWidgets.QPushButton(self.tab_5)
        self.botao_consulta_cpf.setGeometry(QtCore.QRect(186, 290, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.botao_consulta_cpf.setFont(font)
        self.botao_consulta_cpf.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_consulta_cpf.setStyleSheet("border-radius:10px;")
        self.botao_consulta_cpf.setObjectName("botao_consulta_cpf")
        self.botao_pasta_cliente = QtWidgets.QPushButton(self.tab_5)
        self.botao_pasta_cliente.setGeometry(QtCore.QRect(430, 190, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.botao_pasta_cliente.setFont(font)
        self.botao_pasta_cliente.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_pasta_cliente.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botao_pasta_cliente.setObjectName("botao_pasta_cliente")
        self.campo_email = QtWidgets.QLineEdit(self.tab_5)
        self.campo_email.setGeometry(QtCore.QRect(10, 240, 316, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.campo_email.setFont(font)
        self.campo_email.setText("")
        self.campo_email.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.campo_email.setPlaceholderText("")
        self.campo_email.setObjectName("campo_email")
        self.campo_rg = QtWidgets.QLineEdit(self.tab_5)
        self.campo_rg.setGeometry(QtCore.QRect(225, 290, 236, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.campo_rg.setFont(font)
        self.campo_rg.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.campo_rg.setPlaceholderText("")
        self.campo_rg.setObjectName("campo_rg")
        self.label_16 = QtWidgets.QLabel(self.tab_5)
        self.label_16.setGeometry(QtCore.QRect(10, 375, 201, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet("color: #333;")
        self.label_16.setObjectName("label_16")
        self.campo_seguranca_cnh = QtWidgets.QLineEdit(self.tab_5)
        self.campo_seguranca_cnh.setGeometry(QtCore.QRect(10, 390, 206, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.campo_seguranca_cnh.setFont(font)
        self.campo_seguranca_cnh.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.campo_seguranca_cnh.setObjectName("campo_seguranca_cnh")
        self.campo_cnpj_municipio = QtWidgets.QLineEdit(self.tab_5)
        self.campo_cnpj_municipio.setEnabled(True)
        self.campo_cnpj_municipio.setGeometry(QtCore.QRect(225, 390, 166, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.campo_cnpj_municipio.setFont(font)
        self.campo_cnpj_municipio.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.campo_cnpj_municipio.setText("")
        self.campo_cnpj_municipio.setPlaceholderText("")
        self.campo_cnpj_municipio.setObjectName("campo_cnpj_municipio")
        self.campo_cnpj_uf = QtWidgets.QLineEdit(self.tab_5)
        self.campo_cnpj_uf.setEnabled(True)
        self.campo_cnpj_uf.setGeometry(QtCore.QRect(395, 390, 66, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.campo_cnpj_uf.setFont(font)
        self.campo_cnpj_uf.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.campo_cnpj_uf.setText("")
        self.campo_cnpj_uf.setPlaceholderText("")
        self.campo_cnpj_uf.setObjectName("campo_cnpj_uf")
        self.label_25 = QtWidgets.QLabel(self.tab_5)
        self.label_25.setGeometry(QtCore.QRect(225, 375, 129, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet("color: #333;")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.tab_5)
        self.label_26.setGeometry(QtCore.QRect(395, 375, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: #333;")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.tab_5)
        self.label_27.setGeometry(QtCore.QRect(12, 474, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("color: #333;")
        self.label_27.setObjectName("label_27")
        self.campo_diretorio_pasta = QtWidgets.QTextEdit(self.tab_5)
        self.campo_diretorio_pasta.setGeometry(QtCore.QRect(10, 490, 236, 71))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.campo_diretorio_pasta.setFont(font)
        self.campo_diretorio_pasta.setObjectName("campo_diretorio_pasta")
        self.botao_consulta_cnpj = QtWidgets.QPushButton(self.tab_5)
        self.botao_consulta_cnpj.setGeometry(QtCore.QRect(396, 340, 31, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.botao_consulta_cnpj.setFont(font)
        self.botao_consulta_cnpj.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_consulta_cnpj.setStyleSheet("border-radius:10px;")
        self.botao_consulta_cnpj.setObjectName("botao_consulta_cnpj")
        self.line = QtWidgets.QFrame(self.tab_5)
        self.line.setGeometry(QtCore.QRect(-40, 160, 546, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.caminho_pasta = QtWidgets.QLineEdit(self.tab_5)
        self.caminho_pasta.setEnabled(False)
        self.caminho_pasta.setGeometry(QtCore.QRect(10, 635, 451, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.caminho_pasta.setFont(font)
        self.caminho_pasta.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.caminho_pasta.setStyleSheet("")
        self.caminho_pasta.setText("")
        self.caminho_pasta.setObjectName("caminho_pasta")
        self.campo_lista_junta_comercial = QtWidgets.QComboBox(self.tab_5)
        self.campo_lista_junta_comercial.setGeometry(QtCore.QRect(255, 490, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.campo_lista_junta_comercial.setFont(font)
        self.campo_lista_junta_comercial.setStyleSheet("")
        self.campo_lista_junta_comercial.setEditable(False)
        self.campo_lista_junta_comercial.setObjectName("campo_lista_junta_comercial")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.setItemText(0, "")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.campo_lista_junta_comercial.addItem("")
        self.botao_junta = QtWidgets.QPushButton(self.tab_5)
        self.botao_junta.setGeometry(QtCore.QRect(255, 530, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.botao_junta.setFont(font)
        self.botao_junta.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_junta.setStyleSheet("")
        self.botao_junta.setObjectName("botao_junta")
        self.label_28 = QtWidgets.QLabel(self.tab_5)
        self.label_28.setGeometry(QtCore.QRect(260, 475, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("color: #333;")
        self.label_28.setObjectName("label_28")
        self.campo_cnh.raise_()
        self.campo_seguranca_cnh.raise_()
        self.campo_rg.raise_()
        self.campo_lista_status.raise_()
        self.campo_data_agendamento.raise_()
        self.label_17.raise_()
        self.campo_certificado.raise_()
        self.campo_pedido.raise_()
        self.campo_hora_agendamento.raise_()
        self.label_4.raise_()
        self.label_3.raise_()
        self.campo_novo_noBd.raise_()
        self.campo_lista_status_3.raise_()
        self.label_22.raise_()
        self.campo_lista_status_4.raise_()
        self.botao_terminar.raise_()
        self.botao_salvar.raise_()
        self.label_2.raise_()
        self.label.raise_()
        self.label_23.raise_()
        self.barra_progresso_pedido.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.botao_consulta_rg.raise_()
        self.campo_cnpj.raise_()
        self.label_18.raise_()
        self.campo_cpf.raise_()
        self.label_10.raise_()
        self.label_14.raise_()
        self.campo_data_nascimento.raise_()
        self.campo_nome.raise_()
        self.botao_dados_cnpj.raise_()
        self.botao_consulta_cnh.raise_()
        self.label_24.raise_()
        self.campo_nome_mae.raise_()
        self.label_6.raise_()
        self.label_15.raise_()
        self.botao_consulta_cpf.raise_()
        self.botao_pasta_cliente.raise_()
        self.campo_email.raise_()
        self.label_16.raise_()
        self.campo_cnpj_municipio.raise_()
        self.campo_cnpj_uf.raise_()
        self.label_25.raise_()
        self.label_26.raise_()
        self.label_27.raise_()
        self.campo_diretorio_pasta.raise_()
        self.botao_consulta_cnpj.raise_()
        self.line.raise_()
        self.caminho_pasta.raise_()
        self.campo_lista_junta_comercial.raise_()
        self.botao_junta.raise_()
        self.label_28.raise_()
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.botao_procurar = QtWidgets.QPushButton(self.tab_6)
        self.botao_procurar.setGeometry(QtCore.QRect(330, 530, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.botao_procurar.setFont(font)
        self.botao_procurar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_procurar.setStyleSheet("border-radius:10px;\n"
"background-color:rgb(73, 218, 107);\n"
"")
        self.botao_procurar.setObjectName("botao_procurar")
        self.label_quantidade_bd = QtWidgets.QLabel(self.tab_6)
        self.label_quantidade_bd.setGeometry(QtCore.QRect(140, 530, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_quantidade_bd.setFont(font)
        self.label_quantidade_bd.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_quantidade_bd.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_quantidade_bd.setText("")
        self.label_quantidade_bd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_quantidade_bd.setObjectName("label_quantidade_bd")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_6)
        self.tableWidget.setGeometry(QtCore.QRect(10, 100, 451, 421))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.tableWidget.setFont(font)
        self.tableWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(9)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.botao_consultar = QtWidgets.QPushButton(self.tab_6)
        self.botao_consultar.setGeometry(QtCore.QRect(420, 30, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.botao_consultar.setFont(font)
        self.botao_consultar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_consultar.setStyleSheet("")
        self.botao_consultar.setObjectName("botao_consultar")
        self.campo_data_ate = QtWidgets.QDateEdit(self.tab_6)
        self.campo_data_ate.setGeometry(QtCore.QRect(135, 30, 116, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.campo_data_ate.setFont(font)
        self.campo_data_ate.setStyleSheet("")
        self.campo_data_ate.setObjectName("campo_data_ate")
        self.campo_lista_status_2 = QtWidgets.QComboBox(self.tab_6)
        self.campo_lista_status_2.setGeometry(QtCore.QRect(260, 30, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.campo_lista_status_2.setFont(font)
        self.campo_lista_status_2.setStyleSheet("")
        self.campo_lista_status_2.setEditable(False)
        self.campo_lista_status_2.setObjectName("campo_lista_status_2")
        self.campo_lista_status_2.addItem("")
        self.campo_lista_status_2.addItem("")
        self.campo_lista_status_2.addItem("")
        self.campo_lista_status_2.addItem("")
        self.campo_lista_status_2.addItem("")
        self.label_19 = QtWidgets.QLabel(self.tab_6)
        self.label_19.setGeometry(QtCore.QRect(10, 10, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.barra_progresso_consulta = QtWidgets.QProgressBar(self.tab_6)
        self.barra_progresso_consulta.setGeometry(QtCore.QRect(10, 70, 451, 8))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.barra_progresso_consulta.setFont(font)
        self.barra_progresso_consulta.setProperty("value", 0)
        self.barra_progresso_consulta.setAlignment(QtCore.Qt.AlignCenter)
        self.barra_progresso_consulta.setFormat("")
        self.barra_progresso_consulta.setObjectName("barra_progresso_consulta")
        self.label_21 = QtWidgets.QLabel(self.tab_6)
        self.label_21.setGeometry(QtCore.QRect(265, 10, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.campo_data_de = QtWidgets.QDateEdit(self.tab_6)
        self.campo_data_de.setGeometry(QtCore.QRect(10, 30, 116, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.campo_data_de.setFont(font)
        self.campo_data_de.setStyleSheet("")
        self.campo_data_de.setObjectName("campo_data_de")
        self.label_20 = QtWidgets.QLabel(self.tab_6)
        self.label_20.setGeometry(QtCore.QRect(140, 10, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_msg_copiado = QtWidgets.QLabel(self.tab_6)
        self.label_msg_copiado.setGeometry(QtCore.QRect(10, 530, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_msg_copiado.setFont(font)
        self.label_msg_copiado.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_msg_copiado.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_msg_copiado.setText("")
        self.label_msg_copiado.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_msg_copiado.setObjectName("label_msg_copiado")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.campo_msg1 = QtWidgets.QTextEdit(self.tab_2)
        self.campo_msg1.setGeometry(QtCore.QRect(10, 20, 451, 96))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.campo_msg1.setFont(font)
        self.campo_msg1.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.campo_msg1.setStyleSheet("border: 2px solid #031525;\n"
"")
        self.campo_msg1.setObjectName("campo_msg1")
        self.campo_msg3 = QtWidgets.QTextEdit(self.tab_2)
        self.campo_msg3.setGeometry(QtCore.QRect(10, 210, 451, 36))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.campo_msg3.setFont(font)
        self.campo_msg3.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.campo_msg3.setStyleSheet("border: 2px solid #031525;\n"
"")
        self.campo_msg3.setObjectName("campo_msg3")
        self.campo_msg7 = QtWidgets.QTextEdit(self.tab_2)
        self.campo_msg7.setGeometry(QtCore.QRect(10, 440, 451, 61))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.campo_msg7.setFont(font)
        self.campo_msg7.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.campo_msg7.setStyleSheet("border: 2px solid #031525;\n"
"")
        self.campo_msg7.setObjectName("campo_msg7")
        self.campo_msg2 = QtWidgets.QTextEdit(self.tab_2)
        self.campo_msg2.setGeometry(QtCore.QRect(10, 130, 451, 61))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.campo_msg2.setFont(font)
        self.campo_msg2.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.campo_msg2.setStyleSheet("border: 2px solid #031525;\n"
"")
        self.campo_msg2.setObjectName("campo_msg2")
        self.campo_msg6 = QtWidgets.QTextEdit(self.tab_2)
        self.campo_msg6.setGeometry(QtCore.QRect(10, 380, 451, 41))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.campo_msg6.setFont(font)
        self.campo_msg6.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.campo_msg6.setStyleSheet("border: 2px solid #031525;\n"
"")
        self.campo_msg6.setObjectName("campo_msg6")
        self.campo_msg4 = QtWidgets.QTextEdit(self.tab_2)
        self.campo_msg4.setGeometry(QtCore.QRect(10, 260, 451, 36))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.campo_msg4.setFont(font)
        self.campo_msg4.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.campo_msg4.setStyleSheet("border: 2px solid #031525;\n"
"")
        self.campo_msg4.setObjectName("campo_msg4")
        self.campo_msg5 = QtWidgets.QTextEdit(self.tab_2)
        self.campo_msg5.setGeometry(QtCore.QRect(70, 310, 391, 51))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.campo_msg5.setFont(font)
        self.campo_msg5.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.campo_msg5.setStyleSheet("border: 2px solid #031525;\n"
"")
        self.campo_msg5.setObjectName("campo_msg5")
        self.line_2 = QtWidgets.QFrame(self.tab_2)
        self.line_2.setGeometry(QtCore.QRect(30, 320, 41, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.tab_2)
        self.line_3.setGeometry(QtCore.QRect(20, 300, 21, 31))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 10, 451, 111))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(20, 50, 181, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.botao_transf_link_PDF = QtWidgets.QPushButton(self.groupBox_3)
        self.botao_transf_link_PDF.setGeometry(QtCore.QRect(260, 30, 171, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.botao_transf_link_PDF.setFont(font)
        self.botao_transf_link_PDF.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_transf_link_PDF.setObjectName("botao_transf_link_PDF")
        self.campo_link_video = QtWidgets.QLineEdit(self.groupBox_3)
        self.campo_link_video.setGeometry(QtCore.QRect(20, 70, 411, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.campo_link_video.setFont(font)
        self.campo_link_video.setText("")
        self.campo_link_video.setPlaceholderText("")
        self.campo_link_video.setObjectName("campo_link_video")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(10, 125, 451, 326))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.botao_agrupar_PDF = QtWidgets.QPushButton(self.groupBox)
        self.botao_agrupar_PDF.setGeometry(QtCore.QRect(295, 35, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.botao_agrupar_PDF.setFont(font)
        self.botao_agrupar_PDF.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_agrupar_PDF.setStyleSheet("")
        self.botao_agrupar_PDF.setObjectName("botao_agrupar_PDF")
        self.botao_selecionar_arquivos_mesclar = QtWidgets.QPushButton(self.groupBox)
        self.botao_selecionar_arquivos_mesclar.setGeometry(QtCore.QRect(20, 30, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.botao_selecionar_arquivos_mesclar.setFont(font)
        self.botao_selecionar_arquivos_mesclar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_selecionar_arquivos_mesclar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.botao_selecionar_arquivos_mesclar.setStyleSheet("border-radius:10px;")
        self.botao_selecionar_arquivos_mesclar.setObjectName("botao_selecionar_arquivos_mesclar")
        self.botao_limpar_PDF = QtWidgets.QPushButton(self.groupBox)
        self.botao_limpar_PDF.setGeometry(QtCore.QRect(400, 35, 36, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.botao_limpar_PDF.setFont(font)
        self.botao_limpar_PDF.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_limpar_PDF.setStyleSheet("\n"
"border-radius:10px;")
        self.botao_limpar_PDF.setObjectName("botao_limpar_PDF")
        self.barra_progresso_mesclar = QtWidgets.QProgressBar(self.groupBox)
        self.barra_progresso_mesclar.setGeometry(QtCore.QRect(20, 305, 411, 8))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.barra_progresso_mesclar.setFont(font)
        self.barra_progresso_mesclar.setProperty("value", 0)
        self.barra_progresso_mesclar.setAlignment(QtCore.Qt.AlignCenter)
        self.barra_progresso_mesclar.setFormat("")
        self.barra_progresso_mesclar.setObjectName("barra_progresso_mesclar")
        self.label_PDF1 = QtWidgets.QLabel(self.groupBox)
        self.label_PDF1.setGeometry(QtCore.QRect(20, 85, 61, 101))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.label_PDF1.setFont(font)
        self.label_PDF1.setStyleSheet("background-color:rgb(211, 211, 211);")
        self.label_PDF1.setText("")
        self.label_PDF1.setObjectName("label_PDF1")
        self.label_PDF5 = QtWidgets.QLabel(self.groupBox)
        self.label_PDF5.setGeometry(QtCore.QRect(300, 85, 61, 101))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.label_PDF5.setFont(font)
        self.label_PDF5.setStyleSheet("background-color:rgb(211, 211, 211);")
        self.label_PDF5.setText("")
        self.label_PDF5.setObjectName("label_PDF5")
        self.label_PDF4 = QtWidgets.QLabel(self.groupBox)
        self.label_PDF4.setGeometry(QtCore.QRect(230, 85, 61, 101))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.label_PDF4.setFont(font)
        self.label_PDF4.setStyleSheet("background-color:rgb(211, 211, 211);")
        self.label_PDF4.setText("")
        self.label_PDF4.setObjectName("label_PDF4")
        self.label_PDF3 = QtWidgets.QLabel(self.groupBox)
        self.label_PDF3.setGeometry(QtCore.QRect(160, 85, 61, 101))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.label_PDF3.setFont(font)
        self.label_PDF3.setStyleSheet("background-color:rgb(211, 211, 211);")
        self.label_PDF3.setText("")
        self.label_PDF3.setObjectName("label_PDF3")
        self.label_PDF2 = QtWidgets.QLabel(self.groupBox)
        self.label_PDF2.setGeometry(QtCore.QRect(90, 85, 61, 101))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.label_PDF2.setFont(font)
        self.label_PDF2.setStyleSheet("background-color:rgb(211, 211, 211);")
        self.label_PDF2.setText("")
        self.label_PDF2.setObjectName("label_PDF2")
        self.label_PDF6 = QtWidgets.QLabel(self.groupBox)
        self.label_PDF6.setGeometry(QtCore.QRect(370, 85, 61, 101))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.label_PDF6.setFont(font)
        self.label_PDF6.setStyleSheet("background-color:rgb(211, 211, 211);")
        self.label_PDF6.setText("")
        self.label_PDF6.setObjectName("label_PDF6")
        self.label_PDF11 = QtWidgets.QLabel(self.groupBox)
        self.label_PDF11.setGeometry(QtCore.QRect(300, 195, 61, 101))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.label_PDF11.setFont(font)
        self.label_PDF11.setStyleSheet("background-color:rgb(211, 211, 211);")
        self.label_PDF11.setText("")
        self.label_PDF11.setObjectName("label_PDF11")
        self.label_PDF10 = QtWidgets.QLabel(self.groupBox)
        self.label_PDF10.setGeometry(QtCore.QRect(230, 195, 61, 101))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.label_PDF10.setFont(font)
        self.label_PDF10.setStyleSheet("background-color:rgb(211, 211, 211);")
        self.label_PDF10.setText("")
        self.label_PDF10.setObjectName("label_PDF10")
        self.label_PDF7 = QtWidgets.QLabel(self.groupBox)
        self.label_PDF7.setGeometry(QtCore.QRect(20, 195, 61, 101))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.label_PDF7.setFont(font)
        self.label_PDF7.setStyleSheet("background-color:rgb(211, 211, 211);")
        self.label_PDF7.setText("")
        self.label_PDF7.setObjectName("label_PDF7")
        self.label_PDF9 = QtWidgets.QLabel(self.groupBox)
        self.label_PDF9.setGeometry(QtCore.QRect(160, 195, 61, 101))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.label_PDF9.setFont(font)
        self.label_PDF9.setStyleSheet("background-color:rgb(211, 211, 211);")
        self.label_PDF9.setText("")
        self.label_PDF9.setObjectName("label_PDF9")
        self.label_PDF8 = QtWidgets.QLabel(self.groupBox)
        self.label_PDF8.setGeometry(QtCore.QRect(90, 195, 61, 101))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.label_PDF8.setFont(font)
        self.label_PDF8.setStyleSheet("background-color:rgb(211, 211, 211);")
        self.label_PDF8.setText("")
        self.label_PDF8.setObjectName("label_PDF8")
        self.label_PDF12 = QtWidgets.QLabel(self.groupBox)
        self.label_PDF12.setGeometry(QtCore.QRect(370, 195, 61, 101))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.label_PDF12.setFont(font)
        self.label_PDF12.setStyleSheet("background-color:rgb(211, 211, 211);")
        self.label_PDF12.setText("")
        self.label_PDF12.setObjectName("label_PDF12")
        self.campo_lista_nome_doc = QtWidgets.QComboBox(self.groupBox)
        self.campo_lista_nome_doc.setGeometry(QtCore.QRect(65, 35, 221, 31))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.campo_lista_nome_doc.setFont(font)
        self.campo_lista_nome_doc.setStyleSheet("")
        self.campo_lista_nome_doc.setEditable(False)
        self.campo_lista_nome_doc.setObjectName("campo_lista_nome_doc")
        self.campo_lista_nome_doc.addItem("")
        self.campo_lista_nome_doc.setItemText(0, "")
        self.campo_lista_nome_doc.addItem("")
        self.campo_lista_nome_doc.addItem("")
        self.campo_lista_nome_doc.addItem("")
        self.campo_lista_nome_doc.addItem("")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 450, 451, 111))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.botao_converter_jpgPDF = QtWidgets.QPushButton(self.groupBox_2)
        self.botao_converter_jpgPDF.setGeometry(QtCore.QRect(155, 50, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.botao_converter_jpgPDF.setFont(font)
        self.botao_converter_jpgPDF.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.botao_converter_jpgPDF.setStyleSheet("")
        self.botao_converter_jpgPDF.setObjectName("botao_converter_jpgPDF")
        self.pdf_para_jpg = QtWidgets.QRadioButton(self.groupBox_2)
        self.pdf_para_jpg.setGeometry(QtCore.QRect(260, 25, 111, 17))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.pdf_para_jpg.setFont(font)
        self.pdf_para_jpg.setObjectName("pdf_para_jpg")
        self.jpg_para_pdf = QtWidgets.QRadioButton(self.groupBox_2)
        self.jpg_para_pdf.setGeometry(QtCore.QRect(70, 25, 116, 17))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.jpg_para_pdf.setFont(font)
        self.jpg_para_pdf.setCheckable(True)
        self.jpg_para_pdf.setChecked(True)
        self.jpg_para_pdf.setObjectName("jpg_para_pdf")
        self.barra_progresso_jpg = QtWidgets.QProgressBar(self.groupBox_2)
        self.barra_progresso_jpg.setGeometry(QtCore.QRect(20, 90, 411, 8))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.barra_progresso_jpg.setFont(font)
        self.barra_progresso_jpg.setProperty("value", 0)
        self.barra_progresso_jpg.setAlignment(QtCore.Qt.AlignCenter)
        self.barra_progresso_jpg.setFormat("")
        self.barra_progresso_jpg.setObjectName("barra_progresso_jpg")
        self.tabWidget.addTab(self.tab, "")
        janela.setCentralWidget(self.centralwidget)

        self.retranslateUi(janela)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(janela)
        janela.setTabOrder(self.campo_pedido, self.campo_data_agendamento)
        janela.setTabOrder(self.campo_data_agendamento, self.campo_hora_agendamento)
        janela.setTabOrder(self.campo_hora_agendamento, self.campo_certificado)
        janela.setTabOrder(self.campo_certificado, self.campo_lista_status_3)
        janela.setTabOrder(self.campo_lista_status_3, self.campo_lista_status_4)
        janela.setTabOrder(self.campo_lista_status_4, self.campo_lista_status)
        janela.setTabOrder(self.campo_lista_status, self.campo_nome)
        janela.setTabOrder(self.campo_nome, self.campo_email)
        janela.setTabOrder(self.campo_email, self.campo_data_nascimento)
        janela.setTabOrder(self.campo_data_nascimento, self.campo_cpf)
        janela.setTabOrder(self.campo_cpf, self.campo_rg)
        janela.setTabOrder(self.campo_rg, self.campo_cnh)
        janela.setTabOrder(self.campo_cnh, self.campo_cnpj)
        janela.setTabOrder(self.campo_cnpj, self.campo_seguranca_cnh)
        janela.setTabOrder(self.campo_seguranca_cnh, self.campo_nome_mae)
        janela.setTabOrder(self.campo_nome_mae, self.campo_diretorio_pasta)
        janela.setTabOrder(self.campo_diretorio_pasta, self.botao_procurar)
        janela.setTabOrder(self.botao_procurar, self.campo_data_ate)
        janela.setTabOrder(self.campo_data_ate, self.botao_terminar)
        janela.setTabOrder(self.botao_terminar, self.campo_link_video)
        janela.setTabOrder(self.campo_link_video, self.botao_consulta_rg)
        janela.setTabOrder(self.botao_consulta_rg, self.botao_salvar)
        janela.setTabOrder(self.botao_salvar, self.botao_selecionar_arquivos_mesclar)
        janela.setTabOrder(self.botao_selecionar_arquivos_mesclar, self.campo_data_de)
        janela.setTabOrder(self.campo_data_de, self.botao_transf_link_PDF)
        janela.setTabOrder(self.botao_transf_link_PDF, self.botao_dados_cnpj)
        janela.setTabOrder(self.botao_dados_cnpj, self.botao_consulta_cnh)
        janela.setTabOrder(self.botao_consulta_cnh, self.botao_converter_jpgPDF)
        janela.setTabOrder(self.botao_converter_jpgPDF, self.campo_lista_status_2)
        janela.setTabOrder(self.campo_lista_status_2, self.tabWidget)
        janela.setTabOrder(self.tabWidget, self.botao_consulta_cpf)
        janela.setTabOrder(self.botao_consulta_cpf, self.botao_pasta_cliente)
        janela.setTabOrder(self.botao_pasta_cliente, self.botao_agrupar_PDF)
        janela.setTabOrder(self.botao_agrupar_PDF, self.botao_limpar_PDF)
        janela.setTabOrder(self.botao_limpar_PDF, self.botao_consultar)
        janela.setTabOrder(self.botao_consultar, self.campo_cnpj_municipio)
        janela.setTabOrder(self.campo_cnpj_municipio, self.campo_cnpj_uf)
        janela.setTabOrder(self.campo_cnpj_uf, self.botao_consulta_cnpj)
        janela.setTabOrder(self.botao_consulta_cnpj, self.tableWidget)
        janela.setTabOrder(self.tableWidget, self.pdf_para_jpg)
        janela.setTabOrder(self.pdf_para_jpg, self.jpg_para_pdf)

    def retranslateUi(self, janela):
        _translate = QtCore.QCoreApplication.translate
        janela.setWindowTitle(_translate("janela", "MainWindow"))
        self.campo_lista_status.setItemText(0, _translate("janela", "DIGITAÇÃO"))
        self.campo_lista_status.setItemText(1, _translate("janela", "VERIFICAÇÃO"))
        self.campo_lista_status.setItemText(2, _translate("janela", "APROVADO"))
        self.campo_lista_status.setItemText(3, _translate("janela", "CANCELADO"))
        self.label.setText(_translate("janela", "🌟 PEDIDO"))
        self.label_2.setText(_translate("janela", "🌟 TIPO CERTIFICADO"))
        self.label_17.setText(_translate("janela", "🌟 STATUS"))
        self.label_4.setText(_translate("janela", "🌟 HORA AGENDA"))
        self.label_3.setText(_translate("janela", "🌟 DATA AGENDA"))
        self.campo_lista_status_3.setItemText(0, _translate("janela", "NAO"))
        self.campo_lista_status_3.setItemText(1, _translate("janela", "SIM"))
        self.label_22.setText(_translate("janela", "🌟 VENDA?"))
        self.label_23.setText(_translate("janela", "🌟 MODALIDADE"))
        self.campo_lista_status_4.setItemText(1, _translate("janela", "VIDEO"))
        self.campo_lista_status_4.setItemText(2, _translate("janela", "PRESENCIAL"))
        self.botao_terminar.setText(_translate("janela", "FINALIZAR"))
        self.botao_salvar.setText(_translate("janela", "SALVAR"))
        self.label_11.setText(_translate("janela", "e-MAIL"))
        self.label_12.setText(_translate("janela", "NASCIMENTO"))
        self.botao_consulta_rg.setText(_translate("janela", "🔍"))
        self.label_18.setText(_translate("janela", "NOME DA MÃE"))
        self.label_10.setText(_translate("janela", "RG"))
        self.label_14.setText(_translate("janela", "CNPJ"))
        self.botao_dados_cnpj.setText(_translate("janela", "📋"))
        self.botao_consulta_cnh.setText(_translate("janela", "🔍"))
        self.label_24.setText(_translate("janela", "NOME COMPLETO"))
        self.label_6.setText(_translate("janela", "CPF"))
        self.label_15.setText(_translate("janela", "CNH"))
        self.botao_consulta_cpf.setText(_translate("janela", "🔍︎"))
        self.botao_pasta_cliente.setText(_translate("janela", "📂"))
        self.label_16.setText(_translate("janela", "CÓDIGO DE SEGURANÇA - CNH"))
        self.label_25.setText(_translate("janela", "MUNICÍPIO CNPJ"))
        self.label_26.setText(_translate("janela", "UF"))
        self.label_27.setText(_translate("janela", "OBSERVAÇÕES"))
        self.botao_consulta_cnpj.setText(_translate("janela", "🔍"))
        self.campo_lista_junta_comercial.setItemText(1, _translate("janela", "AC"))
        self.campo_lista_junta_comercial.setItemText(2, _translate("janela", "AL"))
        self.campo_lista_junta_comercial.setItemText(3, _translate("janela", "AM"))
        self.campo_lista_junta_comercial.setItemText(4, _translate("janela", "AP"))
        self.campo_lista_junta_comercial.setItemText(5, _translate("janela", "BA"))
        self.campo_lista_junta_comercial.setItemText(6, _translate("janela", "CE"))
        self.campo_lista_junta_comercial.setItemText(7, _translate("janela", "DF"))
        self.campo_lista_junta_comercial.setItemText(8, _translate("janela", "ES"))
        self.campo_lista_junta_comercial.setItemText(9, _translate("janela", "GO"))
        self.campo_lista_junta_comercial.setItemText(10, _translate("janela", "MA"))
        self.campo_lista_junta_comercial.setItemText(11, _translate("janela", "MG"))
        self.campo_lista_junta_comercial.setItemText(12, _translate("janela", "MS"))
        self.campo_lista_junta_comercial.setItemText(13, _translate("janela", "MT"))
        self.campo_lista_junta_comercial.setItemText(14, _translate("janela", "PA"))
        self.campo_lista_junta_comercial.setItemText(15, _translate("janela", "PB"))
        self.campo_lista_junta_comercial.setItemText(16, _translate("janela", "PE"))
        self.campo_lista_junta_comercial.setItemText(17, _translate("janela", "PI"))
        self.campo_lista_junta_comercial.setItemText(18, _translate("janela", "PR"))
        self.campo_lista_junta_comercial.setItemText(19, _translate("janela", "RJ"))
        self.campo_lista_junta_comercial.setItemText(20, _translate("janela", "RN"))
        self.campo_lista_junta_comercial.setItemText(21, _translate("janela", "RO"))
        self.campo_lista_junta_comercial.setItemText(22, _translate("janela", "RR"))
        self.campo_lista_junta_comercial.setItemText(23, _translate("janela", "RS"))
        self.campo_lista_junta_comercial.setItemText(24, _translate("janela", "SC"))
        self.campo_lista_junta_comercial.setItemText(25, _translate("janela", "SE"))
        self.campo_lista_junta_comercial.setItemText(26, _translate("janela", "TO"))
        self.botao_junta.setText(_translate("janela", "IR"))
        self.label_28.setText(_translate("janela", "JUNTA COM."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("janela", "Dados pedido"))
        self.botao_procurar.setText(_translate("janela", "EXPORTAR EXCEL"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("janela", "PEDIDO"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("janela", "NOME"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("janela", "DATA"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("janela", "HORA"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("janela", "MODALIDADE"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("janela", "STATUS"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("janela", "VENDA"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("janela", "TIPO"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("janela", "OBSERVAÇÕES"))
        self.botao_consultar.setText(_translate("janela", "🔍"))
        self.campo_lista_status_2.setItemText(0, _translate("janela", "TODAS"))
        self.campo_lista_status_2.setItemText(1, _translate("janela", "DIGITAÇÃO"))
        self.campo_lista_status_2.setItemText(2, _translate("janela", "VERIFICAÇÃO"))
        self.campo_lista_status_2.setItemText(3, _translate("janela", "APROVADO"))
        self.campo_lista_status_2.setItemText(4, _translate("janela", "CANCELADO"))
        self.label_19.setText(_translate("janela", "DE:"))
        self.label_21.setText(_translate("janela", "STATUS"))
        self.label_20.setText(_translate("janela", "ATÉ:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("janela", "Consulta"))
        self.campo_msg1.setHtml(_translate("janela", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Helvetica\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Helvetica\',\'Helvetica\';\">Olá! tudo bem?</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Helvetica\',\'Helvetica\';\">Preciso de uma foto completa do seu documento de identificação,podendo ser (CNH, RG, OAB),</span><span style=\" font-family:\'Helvetica\',\'Helvetica\'; font-weight:600;\"> FRENTE E VERSO</span><span style=\" font-family:\'Helvetica\',\'Helvetica\';\">.</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Helvetica\',\'Helvetica\';\">--Por favor, retire o documento do plástico e abra-o. </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Helvetica\',\'Helvetica\';\">--O VERSO é a parte que contém o QR code.</span></p></body></html>"))
        self.campo_msg3.setHtml(_translate("janela", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Helvetica\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Helvetica\',\'Helvetica\';\">O senhor é o responsável legal pela empresa perante a Receita Federal?</span></p></body></html>"))
        self.campo_msg7.setHtml(_translate("janela", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Helvetica\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Helvetica\',\'Helvetica\';\">Agradeço pela disponibilidade. Se precisar adquirir mais certificados, pode fazê-lo através do link: </span><a href=\"https://loja.certisign.com.br/?cod_rev=91384\"><span style=\" font-family:\'Helvetica\',\'Helvetica\'; font-weight:600; text-decoration: underline; color:#0000ff;\">https://loja.certisign.com.br/?cod_rev=91384</span></a><span style=\" font-family:\'Helvetica\',\'Helvetica\';\">. Até mais!</span></p></body></html>"))
        self.campo_msg2.setHtml(_translate("janela", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Helvetica\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Helvetica\',\'Helvetica\';\">Irei precisar também do documento de constituição da empresa, podendo ser o</span><span style=\" font-family:\'Helvetica\',\'Helvetica\'; font-weight:600;\"> Contrato Social, Certidão de inteiro teor ,Estatuto social,Requerimento de empresário.</span></p></body></html>"))
        self.campo_msg6.setHtml(_translate("janela", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Helvetica\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Helvetica\',\'Helvetica\';\">Podemos iniciar a vídeo-conferência?</span></p></body></html>"))
        self.campo_msg4.setHtml(_translate("janela", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Helvetica\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Helvetica\',\'Helvetica\';\">Deseja adicionar o número do PIS/CEI ao seu certificado?</span></p></body></html>"))
        self.campo_msg5.setHtml(_translate("janela", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Helvetica\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Helvetica\',\'Helvetica\';\">Caso o senhor tenha funcionário e deseja acessar o e-CAC, será necessário o número do PIS/CEI</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("janela", "Script"))
        self.groupBox_3.setTitle(_translate("janela", "TRANSFORMAR  LINK DA VÍDEO-CONFERÊNCIA  EM   PDF"))
        self.label_7.setText(_translate("janela", "TEXTO"))
        self.botao_transf_link_PDF.setText(_translate("janela", "TRANSFORMAR EM PDF"))
        self.groupBox.setTitle(_translate("janela", "MESCLAR PDF - MAX 5 ARQUIVOS"))
        self.botao_agrupar_PDF.setText(_translate("janela", "MESCLAR PDF"))
        self.botao_selecionar_arquivos_mesclar.setText(_translate("janela", "📂"))
        self.botao_limpar_PDF.setText(_translate("janela", "🗑️"))
        self.campo_lista_nome_doc.setItemText(1, _translate("janela", "CNH COMPLETA"))
        self.campo_lista_nome_doc.setItemText(2, _translate("janela", "RG COMPLETO"))
        self.campo_lista_nome_doc.setItemText(3, _translate("janela", "DOC COMPLETO"))
        self.campo_lista_nome_doc.setItemText(4, _translate("janela", "DOC ADICIONAL"))
        self.groupBox_2.setTitle(_translate("janela", "CONVERSOR"))
        self.botao_converter_jpgPDF.setText(_translate("janela", "CONVERTER"))
        self.pdf_para_jpg.setText(_translate("janela", "PDF > JPG"))
        self.jpg_para_pdf.setText(_translate("janela", "JPG > PDF"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("janela", "PDF"))

